# =============================================================================
# glm_cox_validation.R
#
# Sanity check: Compare Cox log-HR with Poisson-offset log-IRR on survival
# data generated by simulate_rate_trial().
#
# Under the exponential baseline hazard, the two should agree closely.
# This script runs B replications and summarises the agreement.
#
# USAGE: source("dev/glm/glm_cox_validation.R") from the package root, after
#        loading the package with devtools::load_all().
#
# STATUS: dev/glm/ (pre-graduation; not part of the installed package)
# =============================================================================


#' Run the Cox vs. Poisson-Offset Sanity Check
#'
#' Simulates `B` trials with `simulate_rate_trial()`, fits both a Cox model
#' and a Poisson GLM with log(tte) offset on each, and reports the agreement
#' between the log-HR and log-IRR estimates at the ITT level and within the
#' true subgroup.
#'
#' @param B         Integer. Number of simulation replications (default 200).
#' @param n         Integer. Sample size per trial (default 700).
#' @param scenarios Named list of DGM parameter sets.  Each element is a
#'   list of arguments to `simulate_rate_trial()` (excluding `n` and `seed`).
#' @param verbose   Logical. Print progress (default `TRUE`).
#'
#' @return A `data.frame` with columns:
#'   `scenario`, `estimand`, `cox_mean`, `pois_mean`, `bias_mean`,
#'   `bias_sd`, `corr`, `max_abs_diff`.
#'
#' @noRd
run_cox_poisson_validation <- function(
    B         = 200L,
    n         = 700L,
    scenarios = NULL,
    verbose   = TRUE
) {
  if (is.null(scenarios)) {
    scenarios <- list(
      # Scenario 1: Moderate harm in subgroup (x1 == 1 & x3 == 1)
      moderate_harm = list(
        subgroup_defn    = list(x1 = 1, x3 = 1),
        baseline_rate    = 0.10,
        itt_log_irr      = log(0.80),
        subgroup_log_irr = log(2.5),
        cens_range       = c(2, 14)
      ),
      # Scenario 2: Null (no subgroup effect)
      null = list(
        subgroup_defn    = NULL,
        baseline_rate    = 0.10,
        itt_log_irr      = log(0.72),
        subgroup_log_irr = 0,
        cens_range       = c(2, 14)
      ),
      # Scenario 3: High event rate (stress test for Poisson approximation)
      high_events = list(
        subgroup_defn    = list(x1 = 1),
        baseline_rate    = 0.40,
        itt_log_irr      = log(0.70),
        subgroup_log_irr = log(2.0),
        cens_range       = c(1, 5)
      )
    )
  }

  results <- list()

  for (sc_name in names(scenarios)) {
    if (verbose) cat("Scenario:", sc_name, "\n")
    sc_args <- scenarios[[sc_name]]

    # Storage for ITT estimates
    cox_itt  <- numeric(B)
    pois_itt <- numeric(B)
    # Storage for subgroup estimates (if subgroup defined)
    has_sg   <- !is.null(sc_args$subgroup_defn)
    cox_sg   <- pois_sg <- numeric(B)

    for (b in seq_len(B)) {
      df <- do.call(
        simulate_rate_trial,
        c(list(n = n, seed = b), sc_args)
      )

      # ---- Cox log-HR (ITT) ----
      fit_cox <- tryCatch(
        survival::coxph(
          survival::Surv(tte, event) ~ treat,
          data = df
        ),
        error = function(e) NULL
      )
      cox_itt[b] <- if (!is.null(fit_cox)) {
        stats::coef(fit_cox)[["treat"]]
      } else {
        NA_real_
      }

      # ---- Poisson log-IRR (ITT) ----
      fit_pois <- tryCatch(
        stats::glm(
          event ~ treat,
          data   = df,
          family = stats::poisson(link = "log"),
          offset = log(tte)
        ),
        error = function(e) NULL
      )
      pois_itt[b] <- if (!is.null(fit_pois)) {
        stats::coef(fit_pois)[["treat"]]
      } else {
        NA_real_
      }

      # ---- Within true subgroup ----
      if (has_sg) {
        df_sg <- df[df$in_subgroup, ]
        if (nrow(df_sg) >= 20L &&
            sum(df_sg$treat == 0) >= 5L &&
            sum(df_sg$treat == 1) >= 5L) {
          fit_cox_sg <- tryCatch(
            survival::coxph(
              survival::Surv(tte, event) ~ treat,
              data = df_sg
            ),
            error = function(e) NULL
          )
          cox_sg[b] <- if (!is.null(fit_cox_sg)) {
            stats::coef(fit_cox_sg)[["treat"]]
          } else {
            NA_real_
          }

          fit_pois_sg <- tryCatch(
            stats::glm(
              event ~ treat,
              data   = df_sg,
              family = stats::poisson(link = "log"),
              offset = log(tte)
            ),
            error = function(e) NULL
          )
          pois_sg[b] <- if (!is.null(fit_pois_sg)) {
            stats::coef(fit_pois_sg)[["treat"]]
          } else {
            NA_real_
          }
        } else {
          cox_sg[b]  <- NA_real_
          pois_sg[b] <- NA_real_
        }
      }
    }

    # ---- Summarise ITT ----
    ok_itt  <- !is.na(cox_itt) & !is.na(pois_itt)
    diff_itt <- pois_itt[ok_itt] - cox_itt[ok_itt]

    results[[length(results) + 1L]] <- data.frame(
      scenario     = sc_name,
      estimand     = "ITT log-HR vs log-IRR",
      n_valid      = sum(ok_itt),
      cox_mean     = round(mean(cox_itt[ok_itt]), 4),
      pois_mean    = round(mean(pois_itt[ok_itt]), 4),
      bias_mean    = round(mean(diff_itt), 4),
      bias_sd      = round(stats::sd(diff_itt), 4),
      corr         = round(stats::cor(cox_itt[ok_itt], pois_itt[ok_itt]), 4),
      max_abs_diff = round(max(abs(diff_itt)), 4),
      stringsAsFactors = FALSE
    )

    # ---- Summarise subgroup ----
    if (has_sg) {
      ok_sg   <- !is.na(cox_sg) & !is.na(pois_sg)
      diff_sg <- pois_sg[ok_sg] - cox_sg[ok_sg]

      results[[length(results) + 1L]] <- data.frame(
        scenario     = sc_name,
        estimand     = "Subgroup log-HR vs log-IRR",
        n_valid      = sum(ok_sg),
        cox_mean     = round(mean(cox_sg[ok_sg]), 4),
        pois_mean    = round(mean(pois_sg[ok_sg]), 4),
        bias_mean    = round(mean(diff_sg), 4),
        bias_sd      = round(stats::sd(diff_sg), 4),
        corr         = round(stats::cor(cox_sg[ok_sg], pois_sg[ok_sg]), 4),
        max_abs_diff = round(max(abs(diff_sg)), 4),
        stringsAsFactors = FALSE
      )
    }

    if (verbose) {
      cat(sprintf(
        "  ITT:  Cox mean = %.4f, Poisson mean = %.4f, mean diff = %.4f\n",
        mean(cox_itt[ok_itt]), mean(pois_itt[ok_itt]), mean(diff_itt)
      ))
      if (has_sg && sum(ok_sg) > 0L) {
        cat(sprintf(
          "  SG:   Cox mean = %.4f, Poisson mean = %.4f, mean diff = %.4f\n",
          mean(cox_sg[ok_sg]), mean(pois_sg[ok_sg]), mean(diff_sg)
        ))
      }
    }
  }

  out <- do.call(rbind, results)
  rownames(out) <- NULL

  if (verbose) {
    cat("\n==== Summary ====\n")
    print(out, row.names = FALSE)
    cat("\nInterpretation:\n")
    cat("  bias_mean close to 0 => Cox and Poisson agree on average\n")
    cat("  corr close to 1     => estimates track each other closely\n")
    cat("  max_abs_diff small  => no outlier disagreements\n")
  }

  invisible(out)
}


#' Run the Estimator-Closure Sanity Check
#'
#' Verifies that `make_effect_estimator()` returns consistent results for
#' Cox vs. Poisson-offset on the same data slice, using the closure API
#' rather than direct model fitting.  This confirms the closures are wired
#' correctly.
#'
#' @param n    Integer. Sample size (default 500).
#' @param seed Integer. Random seed (default 42).
#'
#' @return A named list with Cox and Poisson closure results.
#'
#' @noRd
run_estimator_closure_check <- function(n = 500L, seed = 42L) {

  df <- simulate_rate_trial(n = n, seed = seed)

  # Build closures
  cox_fn <- make_effect_estimator(
    outcome_type = "survival",
    treat.name   = "treat",
    outcome.name = "tte",
    event.name   = "event"
  )

  pois_fn <- make_effect_estimator(
    outcome_type   = "binary",
    treat.name     = "treat",
    outcome.name   = "event",
    offset.name    = "tte",
    effect_measure = "IRR"
  )

  rd_fn <- make_effect_estimator(
    outcome_type   = "binary",
    treat.name     = "treat",
    outcome.name   = "event",
    effect_measure = "RD"
  )

  # Run on full dataset
  cox_res  <- cox_fn(df)
  pois_res <- pois_fn(df)
  rd_res   <- rd_fn(df)

  cat("== Estimator Closure Sanity Check ==\n\n")
  cat(sprintf("Cox   log-HR:   %.4f (SE %.4f)  [%s]\n",
              cox_res$estimate, cox_res$se, cox_res$method_used))
  cat(sprintf("Pois  log-IRR:  %.4f (SE %.4f)  [%s]\n",
              pois_res$estimate, pois_res$se, pois_res$method_used))
  cat(sprintf("Diff (Pois-Cox): %.4f\n\n",
              pois_res$estimate - cox_res$estimate))
  cat(sprintf("RD estimate:    %.4f (SE %.4f)  [%s]\n",
              rd_res$estimate, rd_res$se, rd_res$method_used))

  # Run on true subgroup
  df_sg <- df[df$in_subgroup, ]
  if (nrow(df_sg) > 20L) {
    cox_sg  <- cox_fn(df_sg)
    pois_sg <- pois_fn(df_sg)
    rd_sg   <- rd_fn(df_sg)

    cat(sprintf("\n-- True subgroup (n = %d) --\n", nrow(df_sg)))
    cat(sprintf("Cox   log-HR:   %.4f (SE %.4f)\n",
                cox_sg$estimate, cox_sg$se))
    cat(sprintf("Pois  log-IRR:  %.4f (SE %.4f)\n",
                pois_sg$estimate, pois_sg$se))
    cat(sprintf("Diff (Pois-Cox): %.4f\n",
                pois_sg$estimate - cox_sg$estimate))
    cat(sprintf("RD estimate:    %.4f (SE %.4f)  [%s]\n",
                rd_sg$estimate, rd_sg$se, rd_sg$method_used))
  }

  invisible(list(
    cox_itt  = cox_res,
    pois_itt = pois_res,
    rd_itt   = rd_res,
    data     = df
  ))
}
