# current_status — `quarto/simulations/gbsg_020`

- **Pin:** `8ad21cf5` on `feature/glm-extension` — HEAD at the time this file was committed; the closeout commit that adds this file is its child.
- **Updated:** 2026-09-24 (closeout of `TASK_section5_full_rerun_2026-09-24`: §2.14, campaign `s5rerun`; curated sections from `status_curated.md`).
- **Generated by** `scripts_dinamr/current_status_regen.R`: the pin and §3 from the directory and from git (§3's table by `scripts_dinamr/status_inventory.R`). Everything else is included verbatim from the hand-maintained `status_curated.md`.
- **Purpose:** a catalog of what has been run in this directory and where the payloads are, so a chat or workstream on another machine can be brought up to speed by attaching this one file. It points at authoritative files; it does not restate their numbers.
- **Maintenance:** regenerated by `scripts_dinamr/current_status_regen.R` as the closeout step of every task that touches this directory. The pin above must equal HEAD at commit time. §3 is generated from the directory and from git, with its table produced by `scripts_dinamr/status_inventory.R`. Everything else comes from `status_curated.md`: edit that file, never `current_status.md`.

---

## 1. The DGM, in one block

- GBSG-based survival simulation. One template: `sim_fs_maxeffCons_fb_mr_field_m1_template.qmd`.
- Cells are (prevalence × target HR × n): prevalence 12.4% (`FS_S7_Z1Q` unset) or 31% (`FS_S7_Z1Q=0.60`); HR 1.50, 1.75 or 1.00; n = 500, 1000, 1500. 2,000 replicates per cell unless stated.
- **HR 1.00 is not a global null.** `FS_S7_HR` calibrates `k_inter` to a target Cox HR inside the planted region. The region rule depends on `FS_S7_Z1Q` alone. At HR 1.00 the planted region carries HR 1.00 against a benefiting complement (HR 0.657 at 12.4%, 0.721 at 31%). Describe it as **differentially null against a benefiting complement**, never with harm vocabulary.
- **There are now TWO designs, and `FS_S7_DGM` selects them** (`TASK_null_gbsg_identification_2026-09-21`). `dgm_model` was the literal `"alt"`, which is why the harness's global-null path used to be unreachable; it is now read from `FS_S7_DGM`, default `"alt"`, so every committed render is unchanged.
  - **`alt`** — everything above: a planted region, `k_inter` calibrated to `FS_S7_HR`, `k_treat = 1`.
  - **`null`** — the **structural null** of §2.8: `.create_gbsg_dgm_()` drops `zh` from the design and sets `flag.harm == 0` with `fs_harm_true = NULL`, so **no region is planted and every subject carries the same treatment effect**. `FS_S7_HR` is then the target **super-population marginal Cox HR** (`dgm$hr_causal`), reached by calibrating `k_treat`; `FS_S7_Z1Q` is rejected, because with no region the quantile would move only the z1 main effect.
  - **Vocabulary, and it matters.** The null design points are fixed by their **marginal Cox HR** (0.657, 0.721), because that is what the alt design's complement effects are. The **patient-level (individual) HR is uniform by construction** — that is what makes it a structural null — but it is a different number, further from 1: **0.582908** at the 0.657 point and **0.656562** at the 0.721 point. Under `null` the AHR equals the patient-level HR exactly, since `loghr_po` is constant. Never call 0.657 "the uniform patient-level HR".
- Seeds are `8316951 + sim_id` throughout, so cells at matched coordinates share DGM draws across campaigns. Verified per cell on both GRF and DINA grids: `n_true` identical on all 2,000 rows, truth agreeing to ≤ 8.9e-15 (cross-machine BLAS; the largest observed is 8.882e-15, on the 31% HR 1.50 / 1.75 cells).

## 2. Campaigns

### 2.1 FS comparators (the reference grid)

| Campaign | Prevalence | Criterion | Cells |
|---|---|---|---|
| `p12ext` | 12.4% | `maxeffCons` ε 0.10 | HR 1.50 (all n); HR 1.00 at n 1000, 1500 |
| `tier2` | 12.4% | `maxeffCons` ε 0.10 | HR 1.75 (all n); HR 1.00 at n 500 |
| `e1stud` | 31% | `effMaxSG` ε 0.20 | HR 1.50 and 1.75 at n 500 |
| `cert20` | 31% | `effMaxSG` ε 0.20 | all others |

- All 18 grid cells are covered, and all 18 designated comparator bundles are verified present. `gate2G.R` now asserts per cell that the designated comparator resolves. The table names the **designated** comparator, the one `gate2G.R` and `fs_extraction.R` resolve to. Earlier FS campaigns (`map1`, `s7`, and others) also hold bundles at some of these cells; those are not the comparator and must not be substituted.
- **Criterion is matched to DINA and GRF at 31% and not at 12.4%.** Any 12.4% cross-identifier gap carries a criterion confound on top of identifier, family construction and detection set.
  - **At 12.4% the confound is the rule, not ε.** `maxeffCons` never reads `effect_neighborhood` on any engine. The "ε 0.10" in the table is the recorded default, and it was inert on those nine cells (`REPORT_partB_measurement_2026-09-12.md`, Stage 0b). Only the informational `band_n` column reads it.
  - **`p12x20` (§2.7) now supplies FS at `effMaxSG` ε 0.20 on the nine 12.4% cells**: the same criterion as DINA and GRF, with MR on and 2,000 replicates per cell. It is **not yet the designated comparator**. `gate2G.R`, `fs_extraction.R` and the summaries still resolve 12.4% to `p12ext` / `tier2`; no script under `scripts_dinamr/` reads `p12x20` except the status generator and the inventory.
- FS one-sided products, recomputed from the committed bundles across **all 12 harm cells**, both prevalences:
  - **field lower on β(Ĥ): 0.941–0.975.** The certification record's 0.944–0.974 is the same quantity on a **smaller cell set**. It predates `p12ext`, which supplies the three 12.4% HR 1.50 cells, and 12.4% HR 1.50 n 1000 (0.9410) is the only harm cell below 0.944. Both are right for their set; quote the cell set with the range.
  - **field-s upper on β(Ĥᶜ): 0.9125–0.9605.** Identical to the record's "0.912–0.960": the endpoints are the same numbers under a different rounding convention, not a disagreement.
  - **Bonferroni joint: unscaled `joint` 0.932–0.964; studentized `joint_s` 0.940–0.964.** The record's "0.939–0.963" is **`joint_s`**, whose 9-cell range is 0.9395–0.9640. `joint` and `joint_s` are different constructions and must be named when quoted.
  - The **six HR 1.00 cells** are a separate cell set; their field-lower values are listed per cell, with the row set named, in `REPORT_grfmr_completion_2026-09-12.md`. Do not fold them into the harm ranges above.
- Classification and bound-location extraction: `REPORT_fs_extraction_2026-09-11.md` (all 18 cells; reading of committed bundles, no re-run).

### 2.2 `dinamr` — DINA, complete

- Engine `dina`, `effMaxSG`, ε 0.20, effect floor log(0.90), no consistency term. 18 of 18 cells, 2,000 replicates.
- Reports: `REPORT_dinamr_*`, `REPORT_dinamr_blockC_2026-09-11.md`. Summary: `summary_dinamr.qmd` / `.html` (18 cells). Review: `REVIEW_dinamr_blockC_2026-09-11.md`.
- DINA's `n_family` is the **surface-proposed candidate set**: small, volatile and shrinking with n. CV runs 0.296–1.458 across all 18 cells; the 1.008–1.458 band quoted in `REPORT_dinamr_blockC` is the **six HR 1.00 cells only**, where it is most extreme.
- **Detection falls with n**, sharply at 12.4%: 0.875 → 0.839 → 0.799 on HR 1.50 harm, 0.908 → 0.907 → 0.898 on HR 1.75 harm, and 0.714 → 0.525 → 0.344 at the null. The overall range across the 18 cells is 0.344–1.000. Every DINA n-trend conditions on a shrinking detection set; say so when reading one.
- On DINA, `admitted_n` is not recorded (the column postdates this campaign), and `n_family` and p̂ are strongly confounded (ρ = −0.47), so the joint count table is needed to read either stratification.

### 2.3 `grfmr` — GRF, complete

- Engine `grf`, `effMaxSG`, ε 0.20, `grf_selection = "frontier"`, `grf_select_statistic = "effect"`, `dmin.grf = 0.0`. **18 of 18 cells**, 2,000 replicates, matching the DINA grid cell for cell.
  - Ten harm cells under `TASK_grfmr_campaign_2026-09-11` (7.939 h).
  - The two deferred 31% HR 1.75 cells and the six HR 1.00 cells under `TASK_grfmr_completion_2026-09-12` (6.425 h against a 6.744 h projection). Nothing deferred, nothing dropped.
- Reports: `REPORT_grfmr_2026-09-11.md`, `REPORT_grfmr_completion_2026-09-12.md`. Per-cell tables: `TABLES_grfmr_completion_2026-09-12.md` (18 cells; supersedes for coverage the 10-cell `TABLES_grfmr_percell_2026-09-12.md`, whose ten cells it reproduces). Summary: `summary_grfmr.qmd` / `.html` (18 of 18, no guarded skips). Reviews: `REVIEW_grfmr_2026-09-12.md` (the ten Part A cells) and `REVIEW_grfmr_completion_2026-09-12.md` (the eight completion cells; accepts the report, no re-run).
- **GRF's `n_family` is the outcome-independent enumerated pool**, not the qualified set. At each n it is identical quantile-for-quantile across both prevalences and all three hazard ratios. The outcome-dependent quantity is **`admitted_n`**, with ρ(`admitted_n`, `n_family`) between +0.016 and +0.054 across all 18 cells.
  - **Stratify GRF on `admitted_n`, never on `n_family`.**
  - `admitted_n` and p̂ carry independent information on GRF (joint counts near-uniform at harm and null cells alike), the opposite of DINA.
- **Detection on the harm cells is 1.0000 at all six 31% cells and 0.9975–1.0000 at 12.4%**, flat in n, so no GRF harm n-trend carries a detection-conditioning caveat.
- **At the HR 1.00 cells the rate is a `selection_rate`.** It is 0.9970 / 0.9980 / 0.9935 at 31%, at 1 within its interval and flat in n. At 12.4% it is 0.9840 / 0.9575 / 0.8675, falling with n through non-detections. **The 12.4% null cells are the only GRF cells whose rate moves with n by more than 0.01**, so a 12.4% null n-trend carries a detection-conditioning qualification. Bound location, not the selection rate, carries the null-cell question: the ≥ 1.00 and ≥ 1.25 shares are in `REPORT_grfmr_completion_2026-09-12.md` with FS beside GRF.
- **Non-detections are separable on GRF.** At the null cells, 13 of 405 non-detections carry `admitted_n = 0` (the empty-admitted-set path) and 392 carry `admitted_n` NA (the re-selection returned before the count). All are `NO-DETECTION`; none is a CONFIG-ERROR.
- Source trace (Gate 0a, 13 sites): GRF's candidates are enumerated from quantiles of X subject to `n_min`, with DR scores entering only the effect column. MR re-evaluates the full enumerated pool, not the forest-qualified subset, and re-applies qualification per draw. This is recorded as a fact about the construction. It sits against handoff §3's description of GRF; that discrepancy is noted, unresolved, and blocks nothing.
- Two floors on two scales: `dmin.grf` is a DR-score pre-filter in RMST units; the binding effect-scale floor on the re-selection path is `hr.threshold = 0.90`, the same floor DINA carries. GRF is not "unfloored" relative to DINA.

### 2.4 `grfprobe` — GRF cost and mechanism

- Five 36-replicate probes. Cost 13.5–19.8 s per replicate, rising with n and prevalence, **flat in family size** (|ρ| ≤ 0.171).
- **Two mechanisms, kept distinct.**
  - **The frontier band cannot empty at `dmin.grf = 0.0`:** the eligible maximum is never negative (`R/subgroup_consistency_helpers.R:784–785`, `R/grf_subgroup_labels.R:358`, `:377–383`). Measured empty on 0 of 180 probe replicates.
  - **The admission floor can empty, and did** (`R/forestsearch_helpers.R:1642–1651`, `admitted_n <- 0L`): on **13 of the 12,000 HR 1.00 replicates**, all at null cells and all non-detections, and on none of the 24,000 harm replicates.
  - Calling the empty-selection branch "unreachable" without that qualifier is wrong: the band cannot empty, the floor can. Stated the same way in `summary_grfmr.qmd` ("The engine").

### 2.5 Part B — identification only: enabled and smoke run (the sweep is §2.6)

**The template (committed `8fd89e1d`).**
- **`FS_S7_MR`:** default `TRUE`, the former literal; `FALSE` gives identification and classification only. It tags the stem `_nomr` and is recorded in meta as `mr_inference`.
- **The focus guard** admits the six Part B criteria: `effMaxSG`, `maxeffCons`, `effMinSG`, `maxSG`, `minSG`, `maxeff`.
- **`FS_S7_NBHD`**, and a non-default `selection_rule`, are rejected unless the focus is `effMaxSG` or `effMinSG`.
- **With MR off**, the recorder reads `label`, `n_sel`, `n_cons_qual` and `band_n` from the `forestsearch()` result. **`n_family` is NA**: it is MR's own fitted family and cannot be recovered without an `R/` change.

**Gate T3: PASS.**
- **Unset:** all 163 non-timing columns and `truth` are `identical()` to the pre-change run.
- **MR off:** the identification and classification columns are `identical()` to MR on.
- **Supplementary:** the DINA and GRF on/off pairs pass too.

**OC smoke `pBoc`.**
- **Setup:** 12.4%, HR 1.50, n 500, 30 replicates, 16 runs, 318 s total.
- **Detection:** set by the engine and flat across criteria.
- **Size and classification:** move with the rule, `maxSG` > `effMaxSG` > `eff` > `effMinSG` ≈ `minSG`.
- **Criterion pairs:** none is identical. On consistency, `maxeffCons`/`maxeff` agree on 27 of 29 replicates and `effMinSG`/`minSG` on 26 of 29.
- **Against committed MR-on bundles:** the selections are identical to `dinamr` / `grfmr` / `p12ext` on sim_id 1–30.
- **Projected 288 cell-runs at 12 workers:** 23.3 / 12.3 / 7.5 h flat, or 37.8 / 19.6 / 11.1 h adjusted for how cost varies across cells, at 2,000 / 1,000 / 500 replicates.
- **Details:** `REPORT_partB_enabling_2026-09-12.md`.

### 2.6 `idsweep` — the Part B identification sweep, complete

- **What it is.** 288 cell-runs: three engines, six criteria, 18 cells.
  - 500 replicates per run: sim_id 1–500, one batch per run, no combine render.
  - MR off (`_nomr`), tag `idsweep`, `campaign.sh`'s knob set. Run on the Mac at 12 workers.
  - **Identification and classification only.** No MR, coverage, bias or bounds.
  - It is a self-contained campaign: no earlier bundle is used as data.
- **Criteria.**
  - Consistency: `effMaxSG` ε 0.20, `effMinSG` ε 0.20, `maxeffCons`, `maxeff`, `maxSG`, `minSG`.
  - DINA and GRF: `effMaxSG` ε 0.20, `effMinSG` ε 0.20, `maxSG`, `minSG`, `eff`. Here `eff` stands for `eff` = `maxeff` = `maxeffCons`, run once.
- **Layout.** Bundles are in `results/` (`*_nomr_idsweep_res_1_500.rds`), renders in the root (`idsweep_*.html`), scripts and logs in `scripts_dinamr/` (`idsweep*`).
- **Outcome.**
  - 18 of 18 cells; nothing deferred, nothing dropped.
  - 12.01 h wall from the start, against a 10.21 h Gate 1 projection. The miss is render overhead: 44.5 s per render against the 16.4 s assumed.
  - Gate A: 288 of 288 runs. Gate I: 18 of 18 cells.
- **Gate I Amendment 1** (applied unattended; for review).
  - Part 1 stopped at cell 1. DINA `maxSG` NPV was NA because the selection was the whole trial, so NPV is 0/0.
  - Under the amendment, a classification rate may be NA on a detected replicate only where its denominator is zero, and each such case is counted.
  - This occurs on DINA `maxSG` only: 12 cells, 2–299 of 500 replicates, and 159–299 at the six 31% harm cells.
- **Detection is set by the engine.**
  - It is flat across criteria in every cell on DINA and GRF.
  - On consistency it is flat except `maxeff`, which detects or selects on 500 of 500 in every cell.
- **Size ordering** holds in all 18 cells on every engine: `maxSG` > `effMaxSG` > `eff` / `maxeffCons` (> `maxeff` on consistency) > `effMinSG` > `minSG`.
- **Criterion agreement** (identical rule over jointly detected replicates).
  - Consistency `maxeffCons` / `maxeff`: 0.869–1.000.
  - Consistency `effMinSG` / `minSG`: 0.208–0.942. It falls with n and with prevalence at the harm cells.
  - Every DINA and GRF pair is lower (medians ≤ 0.457).
- **Same draws.** `n_true` is `identical()` on sim_id 1–500 to every covering committed bundle at every coordinate.
- **Records:** `REPORT_idsweep_2026-09-12.md`, `summary_idsweep.qmd` / `.html`, `scripts_dinamr/logs/idsweep_findings.txt`, `scripts_dinamr/logs/idsweep_walls.txt`.

### 2.7 `p12x20` — Part A: FS at `effMaxSG` ε 0.20, the nine 12.4% cells, complete

- **What it is.** Engine `consistency` (FS), `effMaxSG`, ε 0.20, at the nine 12.4% cells: HR 1.50 / 1.75 / 1.00 × n 500 / 1000 / 1500, cells A1–A9.
  - 2,000 replicates per cell: two seed-disjoint batches of 1,000, then a combine.
  - **MR on:** `ci_method = field`, 5,000 draws. The knobs are listed in each per-cell report: `FS_S7_Z1Q`, `FS_S7_MR` and `FS_S7_FIELD_RECOV` unset; `FS_S7_WORKERS=64`.
  - Tag `p12x20`. Run on pop-os at 64 workers, threads pinned to 1, under R 4.6.1.
- **Layout: different from every other campaign here.**
  - Bundles, renders, per-cell Gate 2 records (`GATE2_p12x20_A*.txt`) and per-cell reports (`REPORT_p12x20_A*.md`) sit together in `p12x20_2026-09-12/`, not in `results/` and the root.
  - Scripts are in `scripts_p12x20/`, logs in `scripts_p12x20/logs/`.
- **Campaign-scoped record: `STATUS_p12x20.md`.** It holds cells, walls, gate counts, the payload inventory and the Stage 0 install record, and makes no pin claim.
- **Stage 0** (`REPORT_p12x20_stage0_2026-09-12.md`). A fresh `devtools::install()` at base `0ab5d1c5`. The O-1 forwarding fix (`1d9401cb`) is verified present in the installed closure, in a fresh session and in a spawned worker.
- **Gate 1** (`REPORT_p12x20_gate1_2026-09-12.md`).
  - Worker count chosen at 64 on per-cell wall-clock, from sweeps at 24 / 48 / 64 / 96.
  - Nine cells projected at 3h45m–8h53m. Per-replicate timing is `fit_mr_secs` alone (see §5 on the `cert20` double count).
- **Stage 2.**
  - 9 of 9 cells. Cell walls sum to 19,788 s; per cell in `STATUS_p12x20.md`.
  - Gate 2 (`scripts_p12x20/gate2F.R`): 66 of 66 checks per cell, 594 in total. The checks are:
    - combine assertions, meta and finiteness
    - interval invariants and the bound identities
    - same draws in two directions: against the committed 12.4% FS bundle (`p12ext` / `tier2`), and against `dinamr` / `grfmr`
- **On FS, `n_cons_qual` and `band_n` are populated**, unlike DINA and GRF.
- **Merged** into `feature/glm-extension` under `TASK_p12x20_merge_2026-09-13`. Its logs (56 files, 106,953 B) are committed under rule 1.

### 2.8 `nullid` — the structural null, identification only, complete

- **What it is.** The strict-null cell the manuscript twice says the design lacks (§5.1 p. 27, §5.4 p. 34): the same GBSG survival design with **no planted region and a uniform treatment benefit**, run for identification and classification only. `TASK_null_gbsg_identification_2026-09-21`; record `REPORT_null_gbsg_identification_2026-09-21.md`.
- **Grid.** 6 cells = 2 uniform effects (marginal Cox HR **0.657**, **0.721**) x n **500 / 1000 / 1500**. **No prevalence dimension** — there is no region, so `FS_S7_Z1Q` is rejected and `z1_quantile` stays at its 0.25 default. 3 identifiers (FS / DINA / GRF) on identical draws within a cell, 2,000 replicates each: **18 runs, 36,000 replicate-searches**.
- **Settings.** `effMaxSG` eps 0.20 — the rule `max_A N(eps)` — on all three engines. Everything else is the campaign's: `hr.threshold` 0.90 (natural scale), `hr.consistency` 0.80, `p*` 0.90, `d0/d1.min` 10, `maxk` 2, `n.min` NULL. MR off (`FS_S7_MR=FALSE`), `FS_S7_FB=none`. **No MR, no bootstrap, no CV, no interval product of any kind** — Gate A asserts per run that all 118 `mr_*` / `fld_*` / `fb_*` columns are NA and `mr_ok == 0`.
- **Run on the Mac** (`Mac-Studio-3.local`, 12 workers, R 4.5.2, forestsearch 0.3.5.9000), as `idsweep` was. 6,909 s of render wall over the 18 runs.
- **Design point, verified before any replicate** (`scripts_dinamr/logs/nullid_designpoint.txt`): prevalence 0 and truth labels absent; `max_g |beta(g) - log HR_uniform|` = 0.000e+00 / 5.551e-17 over the 433 non-empty conjunctions of the 29-factor enumerated family; marginal Cox HR within 1.155e-08 / 2.722e-11 of target.
- **Headline: a region is declared on 13.9% to 98.5% of replicates, under a design in which no subgroup exists.** DINA 0.1390 [0.1245, 0.1549] at `null0657_n1500`; GRF 0.9845 [0.9781, 0.9891] at `null0721_n500`. **Declaration is not evidence that a subgroup exists.**
- The rate **falls with n** on every identifier and is **higher at the weaker uniform benefit** at every n. The mechanism is the HR >= 0.90 screening floor: median candidates clearing it fall 43 -> 16 -> 5 at HR 0.657 and 100 -> 53 -> 26 at HR 0.721, out of ~1,711-1,830 enumerated.
- **`max_g T_g` is not calibrated against the conventional `z_0.95 = 1.645`**: the share exceeding it runs **0.0078 to 0.2077** across the six cells, moving systematically with n and with the effect. It is recorded per replicate so Section 4's calibrated cutoff can be evaluated later **without a re-run**; that evaluation was out of scope here.
- **Conditional specificity is nearly flat (0.7719-0.8502) by arithmetic, not by result**: with an empty planted region it is exactly 1 - |Hhat|/n, and |Hhat|/n sits in 0.150-0.228 in all eighteen runs. Unconditional specificity (0.7878-0.9792) does almost all its work through the declaration rate.
- **Sensitivity and PPV are undefined here** (empty planted region) and are not reported; PPV is 0 by construction on every declaring replicate and must not be quoted as measured. **NPV is 1 by construction.** The identified-to-planted size ratio has no denominator.
- **Two gate bugs, both mine, both corrected, both recorded** — see §7. Neither was a run failure and no bundle was re-run; the final state is 18 of 18 runs with Gate A PASS on every one and Gate C PASS on every cell. The driver's own closing line reads `completed 4 cells ... failed 2`; it is superseded by the report.
- **Recorder additions** (template level, add-only, NA elsewhere): `n_cand_enum`, `n_cand_floor`, `maxT`, `p_sel`, `p_max_qual`, `nv_H_lo1s`; and `nv_H_*` / `nv_Hc_*` are now **populated with MR off** from the search's own Cox refit of the selected region. The first five are **consistency-engine only** — DINA and GRF return neither `find.grps` nor `out_sg$result`.

### 2.9 `nullc125` — the structural null at c1 1.25 / c2 1.00, identification only, complete

- **What it is.** The six `nullid` cells (§2.8) rerun at a stricter screen, **(c1, c2, p*) = (1.25, 1.00, 0.90)**, c1 and c2 passed explicitly; DINA's `m_diff = log(1.25)` and GRF's effect-scale admission floor follow c1, `dmin.grf` 0.0. Everything else is `nullid`'s. `TASK_null_gbsg_thresholds_2026-09-21_v2`; record `REPORT_null_gbsg_thresholds_2026-09-21.md`, which carries the 0.90 / 0.80 rows beside it, read from `nullid`'s bundles.
- **Grid.** 6 cells x 3 identifiers x 2,000 replicates = 18 runs; `effMaxSG` eps 0.20; MR off, `FS_S7_FB=none`. **No MR, bootstrap, CV or interval product of any kind.** Stem token `_c125c100`, campaign tag `nullc125`.
- **Run on pop-os** (64 physical cores, 64 workers, R 4.6.1, forestsearch 0.3.5.9000 built 2026-09-19 03:54 UTC), driver `scripts_dinamr/nullthr.sh` (bash port of `nullid.sh`). 4,002 s of render wall (1.11 h). 18 of 18 runs, Gate A PASS on every one, Gate C PASS on every cell, no halt record.
- **Same draws as `nullid`, across machines:** `nullid`'s `or_Hc_est` (the whole-trial Cox fit under the null) equals `nullc125`'s `itt_est` to <= 8.0e-15 on every row `nullid`'s FS declared.
- **Headline: the stricter screen lowers the false-declaration rate everywhere but not to any nominal level** — FS 0.0070-0.2325, DINA 0.0035-0.2130, GRF 0.0690-0.8350 (from 0.1685-0.6780, 0.1390-0.7400, 0.5645-0.9845 at 0.90 / 0.80). Worst cell `null0721_n500`.
- **But for FS the unconditional rate of a declaration whose unadjusted one-sided 95% lower bound reaches HR 1.00 RISES in every cell** (e.g. 0.1125 -> 0.1910 at `null0721_n500`): removing low-effect candidates moves the `effMaxSG` band onto smaller, higher-effect regions, and 79%-89% of FS's strict-screen declarations carry such a bound. It falls on DINA; on GRF it is unchanged at n 500 and rises at n >= 1000. The count reaching HR 1.25 is identical across screens for FS and GRF in every cell. **A stricter screen is not a remedy for unadjusted claims.**
- `max_g T_g > 1.645` occurs on the same number of replicates on both screens in every cell (0.0065-0.2070 of all 2,000); a fixed 1.645 stays uncalibrated.
- **Template additions (add-only, inert at the default; 169 / 169 columns and truth identical, pre-edit vs knobs unset vs knobs at 0.90 / 0.80):** knobs `FS_S7_C1` / `FS_S7_C2` (both or neither, c2 <= c1); stem token only off the default; meta `c1`, `c2`, `pstar`, `dmin_grf`, `dina_m_diff`; recorder `c1_resolved` / `c2_resolved` (from `args_call_all`; recorded on 2,000 / 2,000 replicates of every run) and `itt_est` / `itt_se` (whole-trial Cox fit, every replicate). **No bundle written before this records its thresholds; those bundles ran 0.90 / 0.80 / 0.90.**
- **For review:** two `nullid_gateA.R` checks that were counts, not invariants (">= 95% of declarers carry the unadjusted estimate"; GRF "`admitted_n` recorded somewhere"), were replaced in `nullthr_gateA.R` by the invariants behind them; details in the report §2. The same rules for sensitivity, PPV, NPV and the size ratio as §2.8.

### 2.10 `nullmr` — the structural null at c1 0.90 / c2 0.80, with MR post-selection inference, complete

- **What it is.** The six `nullid` cells (§2.8) at `nullid`'s screen (threshold knobs unset), **MR on**, per-engine MR knobs exactly as the committed survival campaigns ran them (FS as `p12x20` / cert20; DINA as `dinamr`; GRF as `grfmr`; the only between-engine difference is `FIELD_RECOV`, FS off). `TASK_null_gbsg_mr_2026-09-21`; record `REPORT_null_gbsg_mr_2026-09-21.md`; Step 1 record `scripts_dinamr/logs/nullmr_step1_record.md`.
- **Grid.** 6 cells x 3 identifiers x 2,000 replicates = 18 runs; `effMaxSG` eps 0.20; `FS_S7_FB=none`. Targets β(Ĥ) / β(Ĥᶜ); no oracle (no planted region). Evaluated: naive, IJ two-term (two-sided), field lower on β(Ĥ), field-s upper on β(Ĥᶜ), their Bonferroni pair. Campaign tag `nullmr`; stem carries neither `_nomr` nor a threshold tag.
- **Run on pop-os** (64 workers, R 4.6.1, forestsearch 0.3.5.9000 built 2026-09-19 03:54 UTC), driver `scripts_dinamr/nullmr.sh` (`nullthr.sh` transplant). 19,858 s of render wall (5.52 h) against a 5.55 h projection. 18 of 18 runs, Gate A PASS on every one, Gate C PASS on every cell, no halt. **Template not changed** (the Step 3.3 guard was not needed).
- **MR cannot change identification, checked:** the MR-on smoke equals `nullc125`'s MR-off render of the same replicates on 46 / 46 gated columns and the truth, per identifier. Across machines FS and DINA reproduce `nullid` exactly; GRF differs on 3 of 12,000 replicate-runs (declaration flips; not attributable within scope). MR ran on 21,014 / 21,014 declarations.
- **Headline: the adjusted lower bounds on a false region essentially never reach HR 1.00** — field at most 21 / 2,000 per cell (0.0000-0.0105 unconditional), Bonferroni lower at most 11, IJ at most 4 — against the naive bound's 0.0005-0.1420.
- **Coverage of the false region's own target is not uniform:** field lower on β(Ĥ) GRF 0.939-0.957; FS 0.934-0.974 except **0.879 (`null0657_n1000`) and 0.792 (`null0657_n1500`)**, its two lowest declaration rates; **DINA 0.763-0.879, below nominal everywhere** (conditional on the proposed family). Field-s upper on β(Ĥᶜ) 0.92-0.97 on all three. Bonferroni pair FS 0.899-0.953, GRF 0.934-0.955, DINA 0.827-0.902. IJ two-sided conservative (0.93-1.00). Naive one-sided lower covers β(Ĥ) on 0 of 5,427 FS declarations.
- **For review:** three `nullthr_gateA.R` checks read MR-off-branch-only columns (`nv_H_lo1s`, `p_sel`, `p_max_qual`) and became "NA everywhere" under MR; MR's naive SE (`se_wald`) differs from the MR-off `coxph` SE (point estimate identical), so the naive row and `nullid`'s unadjusted bound are not the same bound. The truths sit 0.02-0.03 below the design target (censored-analysis β), as in §2.9.


### 2.11 `declcal` — the calibrated declaration screen, finite-sample evaluation, complete

- **What it is.** `TASK_declcal_CAMPAIGN_2026-09-22_v2` (file first issued as `TASK_declaration_calibration_evaluation_2026-09-22_v2.md`); record **`dev/reports/REPORT_declaration_calibration_evaluation_2026-09-22.md`** (not in this directory). It evaluates the calibrated screen of `fs_declaration_calibration()` (declare iff `max_g T(g) >= kappa_hat(alpha)`, the `(1 - alpha)` quantile of the multiplier-field maximum `Mstar` over the pre-reduction family) against the conventional p\* 0.90 screen, **as executed** (the rounded rate, `pconsistency.digits = 2`) and at exact z. "Declaration" is the family-wise event only.
- **Grid.** FS only, `effMaxSG` ε 0.20, **c1 = c2 = 1.0**, 2,000 replicates per cell. Block A, boundary null: the **complete null** (`FS_S7_DGM=null`, HR 1 everywhere; `k_treat = 1e-10` because HR 1 is outside `.create_gbsg_dgm_()`'s domain) at n 500 / 1000 / 1500. Block B, interior null: the six `nullid` designs (same seeds). Block C, power: planted harm region (12.4%) at HR 1.5 and 2.0, n 1000 / 1500; the pre-flight firewall (`logs/declcal_preflight.txt`) excluded none.
- **One search per replicate.** `forestsearch()` with MR off, then `fs_mr_inference(keep_declaration_field = TRUE)` on **every** replicate's pre-reduction family (`Z` captured by `trace()` on `subgroup.search`; verified identical to the internal MR capture). Both screens are read post hoc from one `T(g)` vector and one `Mstar`. Centred-Poisson multipliers, **B_cal = 500** (pilot rule). Seeds `8316951 + rep` for data, `seedit` and multipliers.
- **Run on pop-os** (64 workers, forestsearch 0.3.5.9000 built 2026-09-22 19:31 UTC), driver `scripts_dinamr/declcal.sh` (`nullmr.sh` transplant), per-cell runner `declcal_run.R` (template transplant). Pilot `results/declcal_pilot_A2_res_1_200.rds` (A2, 200 replicates; projection 2.67 h vs a 12 h ceiling). Stage 2: 6,011 s (1.67 h), 13 / 13 cells, 0 aborts or errors. **Fidelity gate: the rounded post-reduction rule reproduces the search's own declaration on 26,000 / 26,000 replicates.**
- **Headline.** Boundary null: calibrated α 0.05 rate **0.0475 / 0.0490 / 0.0430** (every Wilson interval contains 0.05) against the conventional screen's **0.92–0.95**; α 0.10 0.105 / 0.095 / 0.084 (conservative at n 1500). Interior null: calibrated ≤ 0.0005 vs conventional 0.007–0.233. Power, planted HR 1.5: calibrated 0.050 / 0.094 vs 0.70 / 0.79; HR 2.0: 0.355 / 0.641 vs 0.96 / 0.99. `kappa_hat_05` ≈ 3.5–3.6 in every cell (implied per-candidate p\* ≈ 0.9996) on families of `G_pre` ≈ 1,200–1,400. Eq. 8 (`alpha_FW_hat`) matches the executed rate within 1.3 paired SE; the calibrated rule never declared where the conventional one did not.
- **Payload.** `results/declcal_{bnull,inull,power}_<cell>_res_1_2000.rds`: `results` (the task's §5 schema, 35 columns), `aux` (the search's own indicator, wall split, floors per fit, replay check), `meta`. Section 3.4's tag column reads the cell id (`A1` …) for these, because the stem's last token is the cell.
- **c0 re-run, `declcalc0` (complete).** `TASK_declcal_c0_campaign_2026-09-22`; record **`dev/reports/REPORT_declcal_c0_campaign_2026-09-22.md`** (not in this directory), with the plug-in approximate table `dev/reports/REPORT_declcal_c0_approx_2026-09-22.md` (payload `results/declcal_c0approx_res.rds`, 120 field captures, B 2000) set beside it. The `declcal` B and C blocks (Block A not re-run) on the same seeds, B_cal 500 and search, with the field capture passing `declaration_c0 = c(0.70, 0.75, 0.80, 0.85)`: the calibrated rule `max_T_pre >= kappa_hat_alpha(c0)` per replicate, c1 = c2 = 1.0 unchanged. Driver `scripts_dinamr/declcalc0.sh`, runner `declcalc0_run.R` (named-line transplants), findings `declcalc0_findings.R` -> `logs/declcalc0_findings.txt`. Smoke B5 × 5; Stage 2 stopped after B1, B2 (committed) and was resumed for B3–C4 with the same driver via `scripts_dinamr/resume/*.cells`; ≈ 4,350 s total, 0 aborts or errors. **Identity gate: 13 c0-independent columns identical to the committed `declcal` payloads on 20,000 / 20,000 replicates**; c0 monotonicity holds on every replicate.
- **c0 headline (α 0.05).** Worst uniform-benefit rate (always B4) 0.0315 / 0.0130 / 0.0040 / 0.0010 at c0 0.70 / 0.75 / 0.80 / 0.85; HR 1.5 power n 1000 0.50 / 0.37 / 0.27 / 0.19, n 1500 0.75 / 0.62 / 0.49 / 0.36; HR 2.0 0.90–0.68 and 0.98–0.88 — against fixed k 2.0 (0.0725; 0.53 / 0.65 / 0.91 / 0.97) and c0 = c2 (0.0005; 0.05 / 0.09 / 0.36 / 0.64). `kappa_hat_05(c0)` falls with n (c0 0.70: 2.45 / 2.07 / 1.76, implied p\* 0.986 / 0.962 / 0.921) and is configuration-invariant to about ±0.03 at fixed n; a literal fixed-p\* re-run at an implied p\* needs `pconsistency.digits >= 5`. Under planted harm ~97% of calibrated declarations admit more than one subgroup, so the re-selection question is live. Payloads `results/declcalc0_{inull,power}_<cell>_res_1_2000.rds` (the `declcal` schema plus per-c0 columns); smoke `results/declcalc0_smoke_B5_res_1_5.rds`.
- **S1.8 payload (`TASK_declcal_c0_summary_2026-09-25`).** Every S1.8 table value computed from the `declcal` / `declcalc0` payloads: CSV `results/declcalc0_summary_tables.csv` (provenance `results/declcalc0_summary_tables.provenance.md`, script `dev/analysis/declcal_c0_summary/declcal_c0_summary.R`); record **`dev/reports/REPORT_declcal_c0_summary_2026-09-25.md`** (not in this directory).

### 2.12 Sibling run outside this directory: `gbsg_app_null`

- **Not a gbsg_020 campaign** (application-matched null DGM on `survival::gbsg` via `generate_aft_dgm_flex(model = "null")`, uniform marginal Cox HR 0.75, the GBSG application's own FS settings, n 686, 1,000 replicates, FS only, no MR): directory `quarto/simulations/gbsg_app_null/`, record **`dev/reports/REPORT_gbsg_app_null_declaration_2026-09-23.md`** (`TASK_gbsg_app_null_declaration_2026-09-23`).
- **p\* grid, same directory (complete).** `TASK_gbsg_pstar_grid_2026-09-23`; record **`dev/reports/REPORT_gbsg_pstar_grid_2026-09-23.md`**. Fixed-baseline (`simulate_from_dgm(baseline = "fixed")`) on the application's own 686 rows, two cells × 5,000 replicates at the floor p\* 0.50 (Cell 1 arm re-randomized at 246/440, Cell 2 observed arm fixed); the full p\* CDF from one run per cell. Driver `run_gbsg_pstar_grid.R`, read-out `pstar_grid_findings.R` -> `logs/pstar_grid_findings.txt`, payloads `results/gbsg_pstar_{gateA,gateB,gateC,cell1,cell2}.*`; 48 workers, 24.2 min for both cells, 0 errors.

### 2.13 `mrs5` — the MR admission alignment's after arm on the 18 Section 5 cells, complete

- **What it is:** the after arm of `7713942e` (MR admits on the screen's rounded consistency threshold) on the 18 FS `effMaxSG` ε 0.20 cells of the manuscript's Section 5 (the nine `p12x20` 12.4% cells, the seven `cert20` 31% cells, the two `e1stud` 31% n 500 harm cells), 200 replicates per cell (sim_id 1–200, seeds `8316951 + sim_id`), FS only, 64 workers. The before arm is the committed bundle of each cell: a `git archive` export of the fix's parent `ba595f4b` reproduced the committed `p12x20` A7, `cert20` HR 1.00 n 500 and `e1stud` HR 1.50 n 500 rows exactly (tag `mrs5pre`).
- **Records:** probe (A7) **`dev/reports/REPORT_mr_alignment_section5_probe_2026-09-23.md`**; sweep (all 18) **`dev/reports/REPORT_mr_alignment_section5_sweep_2026-09-23.md`**. Per-cell read-out `mrs5sweep/readout.md` (`mrs5sweep/readout.R` from `mrs5sweep/pair/*.rds`).
- **Build:** the HEAD build from a scratch library first on `R_LIBS`, asserted per cell from inside 64 workers (`mrs5sweep/logs/*.buildcheck`); the installed library was not used.
- **Tags:** `mrs5probe` (A7, and its Gate T `res_1_10`), `mrs5sweep` (the other 17), `mrs5pre` (parent-build checks, `res_1_10`). Driver `mrs5sweep/sweep.sh` → `mrs5sweep/runcell.sh` → the unchanged `scripts_dinamr/render.sh` and template.

### 2.14 `s5rerun` — the 18 Section 5 FS cells re-run in full under the aligned package, complete

- **What it is:** provenance, not correction. The nine `p12x20`, seven `cert20` and two `e1stud` cells of the manuscript's Section 5, FS `effMaxSG` ε 0.20, re-run at 2,000 replicates each (sim_id 1–2000, seeds `8316951 + sim_id`) from the installed HEAD build (0.3.5.9000, built 2026-09-24 04:00:02 UTC; asserted from inside all 13 workers before every render), so that a re-run from the shipped package reproduces the published numbers. Mac-Studio-3, 13 workers, 18 of 18 cells, 0 errors, 52,658 s wall. The committed bundles are untouched and remain the record of what was published.
- **Layout:** bundles `results/fs_effMaxSG_fb_mr_field_m1_*_nb20_s5rerun_{res_1_1000,res_1001_2000,combined_1_2000}.rds` — the committed stem pattern with the tag changed (the `p12x20` originals sit in `p12x20_2026-09-12/`, these in `results/`). Renders `s5rerun_<cell>_<mode>_<start>.html` in the root. Driver `s5rerun/driver.sh` → `s5rerun/runcell.sh` → the unchanged `scripts_dinamr/render.sh` and template; per-cell record `s5rerun/logs/cells_record.tsv`. Side tags: `s5rerunchk` (Step 2 check, A7, 200 replicates, against `mrs5probe`) and `s5smk1500` (n 1500 memory smoke).
- **Record:** **`dev/reports/REPORT_section5_full_rerun_2026-09-24.md`**; per-cell read-out `s5rerun/readout.md` (`s5rerun/readout.R`); published-range check `s5rerun/ranges.md` (`s5rerun/ranges.R`).
- **What changed:** declaration and selected region are identical on every replicate of every cell. Three quoted range endpoints move by one replicate (0.0005): field-s upper 0.9125 → 0.9130, `joint` 0.9320 → 0.9315, `joint_s` 0.9395 → 0.9400 (the §2.1 ranges, which describe the committed bundles). Per-cell four-decimal coverage and HR 1.00 bound-location medians move by ≤ 0.0016; the ≥ 1.00 / ≥ 1.25 shares do not move.

## 3. Payload inventory

Regenerated from the directory and from git by `scripts_dinamr/current_status_regen.R`; the table in 3.5 by `scripts_dinamr/status_inventory.R`. The commentary after that table, and §1, §2 and §4–§7, are included verbatim from `status_curated.md`.

### 3.1 Where each campaign lives

**The layouts differ.** `dinamr`, `grfmr` and `idsweep` keep bundles in `results/` and renders in the `gbsg_020/` root. `idsweep` has no combined bundles: it is one 500-replicate batch per cell-run, MR off. `p12x20` keeps bundles, renders, per-cell gate records and per-cell reports together in `p12x20_2026-09-12/`, and its campaign-scoped record is `STATUS_p12x20.md`.

| campaign | engine / focus / ε (combined metas) | combined bundles | batch bundles | bundles in | renders (batch + combine) | scripts | campaign documents in `gbsg_020/` |
|---|---|---|---|---|---|---|---|
| `dinamr` | dina / effMaxSG / eps 0.2 | 18 | 36 | `results/` (in `gbsg_020/`) | 54, 235.69 MB, in `gbsg_020/` root | `scripts_dinamr/` (15 files named for it) | `REPORT_dinamr_2026-09-10.md`, `REPORT_dinamr_blockC_2026-09-11.md`, `REPORT_dinamr_stage0_2026-09-10.md`, `REVIEW_dinamr_blockC_2026-09-11.md`, `summary_dinamr.html`, `summary_dinamr.qmd` |
| `grfmr` | grf / effMaxSG / eps 0.2 | 18 | 36 | `results/` (in `gbsg_020/`) | 54, 236.03 MB, in `gbsg_020/` root | `scripts_dinamr/` (22 files named for it) | `REPORT_grfmr_2026-09-11.md`, `REPORT_grfmr_completion_2026-09-12.md`, `REVIEW_grfmr_2026-09-12.md`, `REVIEW_grfmr_completion_2026-09-12.md`, `summary_grfmr.html`, `summary_grfmr.qmd`, `TABLES_grfmr_completion_2026-09-12.md`, `TABLES_grfmr_percell_2026-09-12.md` |
| `p12x20` | consistency / effMaxSG / eps 0.2 | 9 | 18 | `p12x20_2026-09-12/` | 27, 112.16 MB, in `p12x20_2026-09-12/` | `scripts_p12x20/` (4 files named for it) | `LOG_p12x20_progress.txt`, `REPORT_p12x20_gate1_2026-09-12.md`, `REPORT_p12x20_stage0_2026-09-12.md`, `STATUS_p12x20.md` |
| `idsweep` | dina, consistency, grf / maxeffCons, effMaxSG, effMinSG, maxSG, minSG, maxeff / eps 0.1, 0.2 (batch metas; MR off) | 0 | 288 | `results/` (in `gbsg_020/`) | 288, 1089.06 MB, in `gbsg_020/` root | `scripts_dinamr/` (11 files named for it) | `REPORT_idsweep_2026-09-12.md`, `summary_idsweep.html`, `summary_idsweep.qmd` |
| `nullid` | dina, consistency, grf / effMaxSG / eps 0.2 (batch metas; MR off) | 0 | 18 | `results/` (in `gbsg_020/`) | 18, 69.75 MB, in `gbsg_020/` root | `scripts_dinamr/` (7 files named for it) | `REPORT_null_gbsg_identification_2026-09-21.md` |
| `nullc125` | dina, consistency, grf / effMaxSG / eps 0.2 (batch metas; MR off) | 0 | 18 | `results/` (in `gbsg_020/`) | 18, 66.22 MB, in `gbsg_020/` root | `scripts_dinamr/` (8 files named for it) | `REPORT_null_gbsg_thresholds_2026-09-21.md` |
| `nullmr` | dina, consistency, grf / effMaxSG / eps 0.2 (batch metas; MR on) | 0 | 18 | `results/` (in `gbsg_020/`) | 18, 76.93 MB, in `gbsg_020/` root | `scripts_dinamr/` (9 files named for it) | `REPORT_null_gbsg_mr_2026-09-21.md` |
| `declcal` | consistency / effMaxSG / eps 0.2 (batch metas; MR off) | 0 | 13 | `results/` (in `gbsg_020/`) | 0, 0.00 MB, in `gbsg_020/` root | `scripts_dinamr/` (14 files named for it) | `` |
| `declcalc0` | consistency / effMaxSG / eps 0.2 (batch metas; MR off) | 0 | 10 | `results/` (in `gbsg_020/`) | 0, 0.00 MB, in `gbsg_020/` root | `scripts_dinamr/` (7 files named for it) | `` |
| `mrs5` | consistency / effMaxSG / eps 0.2 (batch metas; MR on) | 0 | 18 | `results/` (in `gbsg_020/`) | 22, 93.21 MB, in `gbsg_020/` root | `mrs5sweep/` (7 files named for it) | `` |
| `s5rerun` | consistency / effMaxSG / eps 0.2 | 18 | 36 | `results/` (in `gbsg_020/`) | 56, 252.77 MB, in `gbsg_020/` root | `s5rerun/` (11 files named for it) | `` |

- `p12x20` per-cell gate records and reports: 9 `GATE2_p12x20_*` and 9 `REPORT_p12x20_A*` files in `p12x20_2026-09-12/`.
- `p12x20` campaign-scoped record: `STATUS_p12x20.md` (cells, gate counts, payload inventory, Stage 0 install record); per-cell heartbeat `LOG_p12x20_progress.txt`; runner logs `scripts_p12x20/logs/`.
- `dinamr`, `grfmr` and `idsweep` share `scripts_dinamr/`; `scripts_dinamr/README.md` states each script's role. The script counts above are files whose names match the campaign. `idsweep`'s record is `REPORT_idsweep_2026-09-12.md` with `summary_idsweep.html`; its logs are `scripts_dinamr/logs/idsweep*`.

### 3.2 Cells, from the combined bundle metas (from the batch metas for `idsweep`, which has none)

#### `dinamr` — 18 cells

| cell | prevalence (super-population) | HR | n | rows | sim_id | batches | host | workers | forestsearch | combined bundle | size | tracked |
|---|---|---|---|---|---|---|---|---|---|---|---|---|
| — | 0.12418 | 1.00 | 500 | 2000 | 1-2000 | 2 | Mac-Studio-3.local | 12 | 0.3.5 | `results/dina_effMaxSG_fb_mr_field_m1_h100_knoise0_n500_nb20_dinamr_combined_1_2000.rds` | 1.23 MB | yes |
| — | 0.12418 | 1.00 | 1000 | 2000 | 1-2000 | 2 | Mac-Studio-3.local | 12 | 0.3.5 | `results/dina_effMaxSG_fb_mr_field_m1_h100_knoise0_n1000_nb20_dinamr_combined_1_2000.rds` | 0.96 MB | yes |
| — | 0.12418 | 1.00 | 1500 | 2000 | 1-2000 | 2 | Mac-Studio-3.local | 12 | 0.3.5 | `results/dina_effMaxSG_fb_mr_field_m1_h100_knoise0_n1500_nb20_dinamr_combined_1_2000.rds` | 0.68 MB | yes |
| — | 0.12418 | 1.50 | 500 | 2000 | 1-2000 | 2 | Mac-Studio-3.local | 12 | 0.3.5 | `results/dina_effMaxSG_fb_mr_field_m1_h150_knoise0_n500_nb20_dinamr_combined_1_2000.rds` | 1.43 MB | yes |
| — | 0.12418 | 1.50 | 1000 | 2000 | 1-2000 | 2 | Mac-Studio-3.local | 12 | 0.3.5 | `results/dina_effMaxSG_fb_mr_field_m1_h150_knoise0_n1000_nb20_dinamr_combined_1_2000.rds` | 1.38 MB | yes |
| — | 0.12418 | 1.50 | 1500 | 2000 | 1-2000 | 2 | Mac-Studio-3.local | 12 | 0.3.5 | `results/dina_effMaxSG_fb_mr_field_m1_h150_knoise0_n1500_nb20_dinamr_combined_1_2000.rds` | 1.32 MB | yes |
| — | 0.12418 | 1.75 | 500 | 2000 | 1-2000 | 2 | Mac-Studio-3.local | 12 | 0.3.5 | `results/dina_effMaxSG_fb_mr_field_m1_h175_knoise0_n500_nb20_dinamr_combined_1_2000.rds` | 1.46 MB | yes |
| — | 0.12418 | 1.75 | 1000 | 2000 | 1-2000 | 2 | Mac-Studio-3.local | 12 | 0.3.5 | `results/dina_effMaxSG_fb_mr_field_m1_h175_knoise0_n1000_nb20_dinamr_combined_1_2000.rds` | 1.45 MB | yes |
| — | 0.12418 | 1.75 | 1500 | 2000 | 1-2000 | 2 | Mac-Studio-3.local | 12 | 0.3.5 | `results/dina_effMaxSG_fb_mr_field_m1_h175_knoise0_n1500_nb20_dinamr_combined_1_2000.rds` | 1.42 MB | yes |
| — | 0.30655 | 1.00 | 500 | 2000 | 1-2000 | 2 | Mac-Studio-3.local | 12 | 0.3.5 | `results/dina_effMaxSG_fb_mr_field_m1_h100_knoise0_n500_z1q60_nb20_dinamr_combined_1_2000.rds` | 1.50 MB | yes |
| — | 0.30655 | 1.00 | 1000 | 2000 | 1-2000 | 2 | Mac-Studio-3.local | 12 | 0.3.5 | `results/dina_effMaxSG_fb_mr_field_m1_h100_knoise0_n1000_z1q60_nb20_dinamr_combined_1_2000.rds` | 1.50 MB | yes |
| — | 0.30655 | 1.00 | 1500 | 2000 | 1-2000 | 2 | Mac-Studio-3.local | 12 | 0.3.5 | `results/dina_effMaxSG_fb_mr_field_m1_h100_knoise0_n1500_z1q60_nb20_dinamr_combined_1_2000.rds` | 1.45 MB | yes |
| — | 0.30655 | 1.50 | 500 | 2000 | 1-2000 | 2 | Mac-Studio-3.local | 12 | 0.3.5 | `results/dina_effMaxSG_fb_mr_field_m1_h150_knoise0_n500_z1q60_nb20_dinamr_combined_1_2000.rds` | 1.54 MB | yes |
| — | 0.30655 | 1.50 | 1000 | 2000 | 1-2000 | 2 | Mac-Studio-3.local | 12 | 0.3.5 | `results/dina_effMaxSG_fb_mr_field_m1_h150_knoise0_n1000_z1q60_nb20_dinamr_combined_1_2000.rds` | 1.54 MB | yes |
| — | 0.30655 | 1.50 | 1500 | 2000 | 1-2000 | 2 | Mac-Studio-3.local | 12 | 0.3.5 | `results/dina_effMaxSG_fb_mr_field_m1_h150_knoise0_n1500_z1q60_nb20_dinamr_combined_1_2000.rds` | 1.53 MB | yes |
| — | 0.30655 | 1.75 | 500 | 2000 | 1-2000 | 2 | Mac-Studio-3.local | 12 | 0.3.5 | `results/dina_effMaxSG_fb_mr_field_m1_h175_knoise0_n500_z1q60_nb20_dinamr_combined_1_2000.rds` | 1.54 MB | yes |
| — | 0.30655 | 1.75 | 1000 | 2000 | 1-2000 | 2 | Mac-Studio-3.local | 12 | 0.3.5 | `results/dina_effMaxSG_fb_mr_field_m1_h175_knoise0_n1000_z1q60_nb20_dinamr_combined_1_2000.rds` | 1.53 MB | yes |
| — | 0.30655 | 1.75 | 1500 | 2000 | 1-2000 | 2 | Mac-Studio-3.local | 12 | 0.3.5 | `results/dina_effMaxSG_fb_mr_field_m1_h175_knoise0_n1500_z1q60_nb20_dinamr_combined_1_2000.rds` | 1.52 MB | yes |

#### `grfmr` — 18 cells

| cell | prevalence (super-population) | HR | n | rows | sim_id | batches | host | workers | forestsearch | combined bundle | size | tracked |
|---|---|---|---|---|---|---|---|---|---|---|---|---|
| — | 0.12418 | 1.00 | 500 | 2000 | 1-2000 | 2 | Mac-Studio-3.local | 12 | 0.3.5 | `results/grf_effMaxSG_fb_mr_field_m1_h100_knoise0_n500_nb20_grfmr_combined_1_2000.rds` | 1.53 MB | yes |
| — | 0.12418 | 1.00 | 1000 | 2000 | 1-2000 | 2 | Mac-Studio-3.local | 12 | 0.3.5 | `results/grf_effMaxSG_fb_mr_field_m1_h100_knoise0_n1000_nb20_grfmr_combined_1_2000.rds` | 1.51 MB | yes |
| — | 0.12418 | 1.00 | 1500 | 2000 | 1-2000 | 2 | Mac-Studio-3.local | 12 | 0.3.5 | `results/grf_effMaxSG_fb_mr_field_m1_h100_knoise0_n1500_nb20_grfmr_combined_1_2000.rds` | 1.41 MB | yes |
| — | 0.12418 | 1.50 | 500 | 2000 | 1-2000 | 2 | Mac-Studio-3.local | 12 | 0.3.5 | `results/grf_effMaxSG_fb_mr_field_m1_h150_knoise0_n500_nb20_grfmr_combined_1_2000.rds` | 1.54 MB | yes |
| — | 0.12418 | 1.50 | 1000 | 2000 | 1-2000 | 2 | Mac-Studio-3.local | 12 | 0.3.5 | `results/grf_effMaxSG_fb_mr_field_m1_h150_knoise0_n1000_nb20_grfmr_combined_1_2000.rds` | 1.53 MB | yes |
| — | 0.12418 | 1.50 | 1500 | 2000 | 1-2000 | 2 | Mac-Studio-3.local | 12 | 0.3.5 | `results/grf_effMaxSG_fb_mr_field_m1_h150_knoise0_n1500_nb20_grfmr_combined_1_2000.rds` | 1.53 MB | yes |
| — | 0.12418 | 1.75 | 500 | 2000 | 1-2000 | 2 | Mac-Studio-3.local | 12 | 0.3.5 | `results/grf_effMaxSG_fb_mr_field_m1_h175_knoise0_n500_nb20_grfmr_combined_1_2000.rds` | 1.53 MB | yes |
| — | 0.12418 | 1.75 | 1000 | 2000 | 1-2000 | 2 | Mac-Studio-3.local | 12 | 0.3.5 | `results/grf_effMaxSG_fb_mr_field_m1_h175_knoise0_n1000_nb20_grfmr_combined_1_2000.rds` | 1.52 MB | yes |
| — | 0.12418 | 1.75 | 1500 | 2000 | 1-2000 | 2 | Mac-Studio-3.local | 12 | 0.3.5 | `results/grf_effMaxSG_fb_mr_field_m1_h175_knoise0_n1500_nb20_grfmr_combined_1_2000.rds` | 1.52 MB | yes |
| — | 0.30655 | 1.00 | 500 | 2000 | 1-2000 | 2 | Mac-Studio-3.local | 12 | 0.3.5 | `results/grf_effMaxSG_fb_mr_field_m1_h100_knoise0_n500_z1q60_nb20_grfmr_combined_1_2000.rds` | 1.54 MB | yes |
| — | 0.30655 | 1.00 | 1000 | 2000 | 1-2000 | 2 | Mac-Studio-3.local | 12 | 0.3.5 | `results/grf_effMaxSG_fb_mr_field_m1_h100_knoise0_n1000_z1q60_nb20_grfmr_combined_1_2000.rds` | 1.55 MB | yes |
| — | 0.30655 | 1.00 | 1500 | 2000 | 1-2000 | 2 | Mac-Studio-3.local | 12 | 0.3.5 | `results/grf_effMaxSG_fb_mr_field_m1_h100_knoise0_n1500_z1q60_nb20_grfmr_combined_1_2000.rds` | 1.54 MB | yes |
| — | 0.30655 | 1.50 | 500 | 2000 | 1-2000 | 2 | Mac-Studio-3.local | 12 | 0.3.5 | `results/grf_effMaxSG_fb_mr_field_m1_h150_knoise0_n500_z1q60_nb20_grfmr_combined_1_2000.rds` | 1.53 MB | yes |
| — | 0.30655 | 1.50 | 1000 | 2000 | 1-2000 | 2 | Mac-Studio-3.local | 12 | 0.3.5 | `results/grf_effMaxSG_fb_mr_field_m1_h150_knoise0_n1000_z1q60_nb20_grfmr_combined_1_2000.rds` | 1.53 MB | yes |
| — | 0.30655 | 1.50 | 1500 | 2000 | 1-2000 | 2 | Mac-Studio-3.local | 12 | 0.3.5 | `results/grf_effMaxSG_fb_mr_field_m1_h150_knoise0_n1500_z1q60_nb20_grfmr_combined_1_2000.rds` | 1.52 MB | yes |
| — | 0.30655 | 1.75 | 500 | 2000 | 1-2000 | 2 | Mac-Studio-3.local | 12 | 0.3.5 | `results/grf_effMaxSG_fb_mr_field_m1_h175_knoise0_n500_z1q60_nb20_grfmr_combined_1_2000.rds` | 1.53 MB | yes |
| — | 0.30655 | 1.75 | 1000 | 2000 | 1-2000 | 2 | Mac-Studio-3.local | 12 | 0.3.5 | `results/grf_effMaxSG_fb_mr_field_m1_h175_knoise0_n1000_z1q60_nb20_grfmr_combined_1_2000.rds` | 1.52 MB | yes |
| — | 0.30655 | 1.75 | 1500 | 2000 | 1-2000 | 2 | Mac-Studio-3.local | 12 | 0.3.5 | `results/grf_effMaxSG_fb_mr_field_m1_h175_knoise0_n1500_z1q60_nb20_grfmr_combined_1_2000.rds` | 1.51 MB | yes |

#### `p12x20` — 9 cells

| cell | prevalence (super-population) | HR | n | rows | sim_id | batches | host | workers | forestsearch | combined bundle | size | tracked |
|---|---|---|---|---|---|---|---|---|---|---|---|---|
| A7 | 0.12418 | 1.00 | 500 | 2000 | 1-2000 | 2 | pop-os | 64 | 0.3.5 | `p12x20_2026-09-12/fs_effMaxSG_fb_mr_field_m1_h100_knoise0_n500_nb20_p12x20_combined_1_2000.rds` | 1.11 MB | yes |
| A8 | 0.12418 | 1.00 | 1000 | 2000 | 1-2000 | 2 | pop-os | 64 | 0.3.5 | `p12x20_2026-09-12/fs_effMaxSG_fb_mr_field_m1_h100_knoise0_n1000_nb20_p12x20_combined_1_2000.rds` | 1.08 MB | yes |
| A9 | 0.12418 | 1.00 | 1500 | 2000 | 1-2000 | 2 | pop-os | 64 | 0.3.5 | `p12x20_2026-09-12/fs_effMaxSG_fb_mr_field_m1_h100_knoise0_n1500_nb20_p12x20_combined_1_2000.rds` | 1.03 MB | yes |
| A1 | 0.12418 | 1.50 | 500 | 2000 | 1-2000 | 2 | pop-os | 64 | 0.3.5 | `p12x20_2026-09-12/fs_effMaxSG_fb_mr_field_m1_h150_knoise0_n500_nb20_p12x20_combined_1_2000.rds` | 1.38 MB | yes |
| A2 | 0.12418 | 1.50 | 1000 | 2000 | 1-2000 | 2 | pop-os | 64 | 0.3.5 | `p12x20_2026-09-12/fs_effMaxSG_fb_mr_field_m1_h150_knoise0_n1000_nb20_p12x20_combined_1_2000.rds` | 1.43 MB | yes |
| A3 | 0.12418 | 1.50 | 1500 | 2000 | 1-2000 | 2 | pop-os | 64 | 0.3.5 | `p12x20_2026-09-12/fs_effMaxSG_fb_mr_field_m1_h150_knoise0_n1500_nb20_p12x20_combined_1_2000.rds` | 1.43 MB | yes |
| A4 | 0.12418 | 1.75 | 500 | 2000 | 1-2000 | 2 | pop-os | 64 | 0.3.5 | `p12x20_2026-09-12/fs_effMaxSG_fb_mr_field_m1_h175_knoise0_n500_nb20_p12x20_combined_1_2000.rds` | 1.42 MB | yes |
| A5 | 0.12418 | 1.75 | 1000 | 2000 | 1-2000 | 2 | pop-os | 64 | 0.3.5 | `p12x20_2026-09-12/fs_effMaxSG_fb_mr_field_m1_h175_knoise0_n1000_nb20_p12x20_combined_1_2000.rds` | 1.44 MB | yes |
| A6 | 0.12418 | 1.75 | 1500 | 2000 | 1-2000 | 2 | pop-os | 64 | 0.3.5 | `p12x20_2026-09-12/fs_effMaxSG_fb_mr_field_m1_h175_knoise0_n1500_nb20_p12x20_combined_1_2000.rds` | 1.42 MB | yes |

#### `idsweep` — 18 cells (no combined bundles: one batch bundle per cell-run)

| cell | prevalence (super-population) | HR | n | rows per run | sim_id | runs (batch bundles) | host | workers | forestsearch | first batch bundle | total size | tracked (all) |
|---|---|---|---|---|---|---|---|---|---|---|---|---|
| — | 0.12418 | 1.00 | 500 | 500 | 1-500 | 16 | Mac-Studio-3.local | 12 | 0.3.5 | `results/dina_eff_fb_mr_field_m1_h100_knoise0_n500_nomr_idsweep_res_1_500.rds` | 0.88 MB | yes |
| — | 0.12418 | 1.00 | 1000 | 500 | 1-500 | 16 | Mac-Studio-3.local | 12 | 0.3.5 | `results/dina_eff_fb_mr_field_m1_h100_knoise0_n1000_nomr_idsweep_res_1_500.rds` | 0.84 MB | yes |
| — | 0.12418 | 1.00 | 1500 | 500 | 1-500 | 16 | Mac-Studio-3.local | 12 | 0.3.5 | `results/dina_eff_fb_mr_field_m1_h100_knoise0_n1500_nomr_idsweep_res_1_500.rds` | 0.74 MB | yes |
| — | 0.12418 | 1.50 | 500 | 500 | 1-500 | 16 | Mac-Studio-3.local | 12 | 0.3.5 | `results/dina_eff_fb_mr_field_m1_h150_knoise0_n500_nomr_idsweep_res_1_500.rds` | 0.96 MB | yes |
| — | 0.12418 | 1.50 | 1000 | 500 | 1-500 | 16 | Mac-Studio-3.local | 12 | 0.3.5 | `results/dina_eff_fb_mr_field_m1_h150_knoise0_n1000_nomr_idsweep_res_1_500.rds` | 0.94 MB | yes |
| — | 0.12418 | 1.50 | 1500 | 500 | 1-500 | 16 | Mac-Studio-3.local | 12 | 0.3.5 | `results/dina_eff_fb_mr_field_m1_h150_knoise0_n1500_nomr_idsweep_res_1_500.rds` | 0.91 MB | yes |
| — | 0.12418 | 1.75 | 500 | 500 | 1-500 | 16 | Mac-Studio-3.local | 12 | 0.3.5 | `results/dina_eff_fb_mr_field_m1_h175_knoise0_n500_nomr_idsweep_res_1_500.rds` | 0.96 MB | yes |
| — | 0.12418 | 1.75 | 1000 | 500 | 1-500 | 16 | Mac-Studio-3.local | 12 | 0.3.5 | `results/dina_eff_fb_mr_field_m1_h175_knoise0_n1000_nomr_idsweep_res_1_500.rds` | 0.94 MB | yes |
| — | 0.12418 | 1.75 | 1500 | 500 | 1-500 | 16 | Mac-Studio-3.local | 12 | 0.3.5 | `results/dina_eff_fb_mr_field_m1_h175_knoise0_n1500_nomr_idsweep_res_1_500.rds` | 0.92 MB | yes |
| — | 0.30655 | 1.00 | 500 | 500 | 1-500 | 16 | Mac-Studio-3.local | 12 | 0.3.5 | `results/dina_eff_fb_mr_field_m1_h100_knoise0_n500_z1q60_nomr_idsweep_res_1_500.rds` | 1.01 MB | yes |
| — | 0.30655 | 1.00 | 1000 | 500 | 1-500 | 16 | Mac-Studio-3.local | 12 | 0.3.5 | `results/dina_eff_fb_mr_field_m1_h100_knoise0_n1000_z1q60_nomr_idsweep_res_1_500.rds` | 1.01 MB | yes |
| — | 0.30655 | 1.00 | 1500 | 500 | 1-500 | 16 | Mac-Studio-3.local | 12 | 0.3.5 | `results/dina_eff_fb_mr_field_m1_h100_knoise0_n1500_z1q60_nomr_idsweep_res_1_500.rds` | 1.00 MB | yes |
| — | 0.30655 | 1.50 | 500 | 500 | 1-500 | 16 | Mac-Studio-3.local | 12 | 0.3.5 | `results/dina_eff_fb_mr_field_m1_h150_knoise0_n500_z1q60_nomr_idsweep_res_1_500.rds` | 1.00 MB | yes |
| — | 0.30655 | 1.50 | 1000 | 500 | 1-500 | 16 | Mac-Studio-3.local | 12 | 0.3.5 | `results/dina_eff_fb_mr_field_m1_h150_knoise0_n1000_z1q60_nomr_idsweep_res_1_500.rds` | 0.98 MB | yes |
| — | 0.30655 | 1.50 | 1500 | 500 | 1-500 | 16 | Mac-Studio-3.local | 12 | 0.3.5 | `results/dina_eff_fb_mr_field_m1_h150_knoise0_n1500_z1q60_nomr_idsweep_res_1_500.rds` | 0.96 MB | yes |
| — | 0.30655 | 1.75 | 500 | 500 | 1-500 | 16 | Mac-Studio-3.local | 12 | 0.3.5 | `results/dina_eff_fb_mr_field_m1_h175_knoise0_n500_z1q60_nomr_idsweep_res_1_500.rds` | 0.98 MB | yes |
| — | 0.30655 | 1.75 | 1000 | 500 | 1-500 | 16 | Mac-Studio-3.local | 12 | 0.3.5 | `results/dina_eff_fb_mr_field_m1_h175_knoise0_n1000_z1q60_nomr_idsweep_res_1_500.rds` | 0.95 MB | yes |
| — | 0.30655 | 1.75 | 1500 | 500 | 1-500 | 16 | Mac-Studio-3.local | 12 | 0.3.5 | `results/dina_eff_fb_mr_field_m1_h175_knoise0_n1500_z1q60_nomr_idsweep_res_1_500.rds` | 0.94 MB | yes |

#### `nullid` — 6 cells (no combined bundles: one batch bundle per cell-run)

| cell | prevalence (super-population) | HR | n | rows per run | sim_id | runs (batch bundles) | host | workers | forestsearch | first batch bundle | total size | tracked (all) |
|---|---|---|---|---|---|---|---|---|---|---|---|---|
| — | 0.00000 | 0.657 | 500 | 2000 | 1-2000 | 3 | Mac-Studio-3.local | 12 | 0.3.5.9000 | `results/dina_effMaxSG_fb_mr_field_m1_h066_knoise0_n500_null657_nb20_nomr_nullid_res_1_2000.rds` | 0.63 MB | yes |
| — | 0.00000 | 0.657 | 1000 | 2000 | 1-2000 | 3 | Mac-Studio-3.local | 12 | 0.3.5.9000 | `results/dina_effMaxSG_fb_mr_field_m1_h066_knoise0_n1000_null657_nb20_nomr_nullid_res_1_2000.rds` | 0.50 MB | yes |
| — | 0.00000 | 0.657 | 1500 | 2000 | 1-2000 | 3 | Mac-Studio-3.local | 12 | 0.3.5.9000 | `results/dina_effMaxSG_fb_mr_field_m1_h066_knoise0_n1500_null657_nb20_nomr_nullid_res_1_2000.rds` | 0.35 MB | yes |
| — | 0.00000 | 0.721 | 500 | 2000 | 1-2000 | 3 | Mac-Studio-3.local | 12 | 0.3.5.9000 | `results/dina_effMaxSG_fb_mr_field_m1_h072_knoise0_n500_null721_nb20_nomr_nullid_res_1_2000.rds` | 0.74 MB | yes |
| — | 0.00000 | 0.721 | 1000 | 2000 | 1-2000 | 3 | Mac-Studio-3.local | 12 | 0.3.5.9000 | `results/dina_effMaxSG_fb_mr_field_m1_h072_knoise0_n1000_null721_nb20_nomr_nullid_res_1_2000.rds` | 0.68 MB | yes |
| — | 0.00000 | 0.721 | 1500 | 2000 | 1-2000 | 3 | Mac-Studio-3.local | 12 | 0.3.5.9000 | `results/dina_effMaxSG_fb_mr_field_m1_h072_knoise0_n1500_null721_nb20_nomr_nullid_res_1_2000.rds` | 0.58 MB | yes |

#### `nullc125` — 6 cells (no combined bundles: one batch bundle per cell-run)

| cell | prevalence (super-population) | HR | n | rows per run | sim_id | runs (batch bundles) | host | workers | forestsearch | first batch bundle | total size | tracked (all) |
|---|---|---|---|---|---|---|---|---|---|---|---|---|
| — | 0.00000 | 0.657 | 500 | 2000 | 1-2000 | 3 | pop-os | 64 | 0.3.5.9000 | `results/dina_effMaxSG_fb_mr_field_m1_h066_knoise0_n500_null657_nb20_nomr_c125c100_nullc125_res_1_2000.rds` | 0.44 MB | yes |
| — | 0.00000 | 0.657 | 1000 | 2000 | 1-2000 | 3 | pop-os | 64 | 0.3.5.9000 | `results/dina_effMaxSG_fb_mr_field_m1_h066_knoise0_n1000_null657_nb20_nomr_c125c100_nullc125_res_1_2000.rds` | 0.27 MB | yes |
| — | 0.00000 | 0.657 | 1500 | 2000 | 1-2000 | 3 | pop-os | 64 | 0.3.5.9000 | `results/dina_effMaxSG_fb_mr_field_m1_h066_knoise0_n1500_null657_nb20_nomr_c125c100_nullc125_res_1_2000.rds` | 0.19 MB | yes |
| — | 0.00000 | 0.721 | 500 | 2000 | 1-2000 | 3 | pop-os | 64 | 0.3.5.9000 | `results/dina_effMaxSG_fb_mr_field_m1_h072_knoise0_n500_null721_nb20_nomr_c125c100_nullc125_res_1_2000.rds` | 0.55 MB | yes |
| — | 0.00000 | 0.721 | 1000 | 2000 | 1-2000 | 3 | pop-os | 64 | 0.3.5.9000 | `results/dina_effMaxSG_fb_mr_field_m1_h072_knoise0_n1000_null721_nb20_nomr_c125c100_nullc125_res_1_2000.rds` | 0.38 MB | yes |
| — | 0.00000 | 0.721 | 1500 | 2000 | 1-2000 | 3 | pop-os | 64 | 0.3.5.9000 | `results/dina_effMaxSG_fb_mr_field_m1_h072_knoise0_n1500_null721_nb20_nomr_c125c100_nullc125_res_1_2000.rds` | 0.24 MB | yes |

#### `nullmr` — 6 cells (no combined bundles: one batch bundle per cell-run)

| cell | prevalence (super-population) | HR | n | rows per run | sim_id | runs (batch bundles) | host | workers | forestsearch | first batch bundle | total size | tracked (all) |
|---|---|---|---|---|---|---|---|---|---|---|---|---|
| — | 0.00000 | 0.657 | 500 | 2000 | 1-2000 | 3 | pop-os | 64 | 0.3.5.9000 | `results/dina_effMaxSG_fb_mr_field_m1_h066_knoise0_n500_null657_nb20_nullmr_res_1_2000.rds` | 3.23 MB | yes |
| — | 0.00000 | 0.657 | 1000 | 2000 | 1-2000 | 3 | pop-os | 64 | 0.3.5.9000 | `results/dina_effMaxSG_fb_mr_field_m1_h066_knoise0_n1000_null657_nb20_nullmr_res_1_2000.rds` | 2.54 MB | yes |
| — | 0.00000 | 0.657 | 1500 | 2000 | 1-2000 | 3 | pop-os | 64 | 0.3.5.9000 | `results/dina_effMaxSG_fb_mr_field_m1_h066_knoise0_n1500_null657_nb20_nullmr_res_1_2000.rds` | 1.70 MB | yes |
| — | 0.00000 | 0.721 | 500 | 2000 | 1-2000 | 3 | pop-os | 64 | 0.3.5.9000 | `results/dina_effMaxSG_fb_mr_field_m1_h072_knoise0_n500_null721_nb20_nullmr_res_1_2000.rds` | 3.80 MB | yes |
| — | 0.00000 | 0.721 | 1000 | 2000 | 1-2000 | 3 | pop-os | 64 | 0.3.5.9000 | `results/dina_effMaxSG_fb_mr_field_m1_h072_knoise0_n1000_null721_nb20_nullmr_res_1_2000.rds` | 3.46 MB | yes |
| — | 0.00000 | 0.721 | 1500 | 2000 | 1-2000 | 3 | pop-os | 64 | 0.3.5.9000 | `results/dina_effMaxSG_fb_mr_field_m1_h072_knoise0_n1500_null721_nb20_nullmr_res_1_2000.rds` | 2.90 MB | yes |

#### `declcal` — 13 cells (no combined bundles: one batch bundle per cell-run)

| cell | prevalence (super-population) | HR | n | rows per run | sim_id | runs (batch bundles) | host | workers | forestsearch | first batch bundle | total size | tracked (all) |
|---|---|---|---|---|---|---|---|---|---|---|---|---|
| B1 | 0.00000 | 0.657 | 500 | 2000 | 1-2000 | 1 | pop-os | 64 | 0.3.5.9000 | `results/declcal_inull_B1_res_1_2000.rds` | 0.17 MB | yes |
| B2 | 0.00000 | 0.657 | 1000 | 2000 | 1-2000 | 1 | pop-os | 64 | 0.3.5.9000 | `results/declcal_inull_B2_res_1_2000.rds` | 0.17 MB | yes |
| B3 | 0.00000 | 0.657 | 1500 | 2000 | 1-2000 | 1 | pop-os | 64 | 0.3.5.9000 | `results/declcal_inull_B3_res_1_2000.rds` | 0.17 MB | yes |
| B4 | 0.00000 | 0.721 | 500 | 2000 | 1-2000 | 1 | pop-os | 64 | 0.3.5.9000 | `results/declcal_inull_B4_res_1_2000.rds` | 0.17 MB | yes |
| B5 | 0.00000 | 0.721 | 1000 | 2000 | 1-2000 | 1 | pop-os | 64 | 0.3.5.9000 | `results/declcal_inull_B5_res_1_2000.rds` | 0.17 MB | yes |
| B6 | 0.00000 | 0.721 | 1500 | 2000 | 1-2000 | 1 | pop-os | 64 | 0.3.5.9000 | `results/declcal_inull_B6_res_1_2000.rds` | 0.17 MB | yes |
| A1 | 0.00000 | 1.000 | 500 | 2000 | 1-2000 | 1 | pop-os | 64 | 0.3.5.9000 | `results/declcal_bnull_A1_res_1_2000.rds` | 0.18 MB | yes |
| A2 | 0.00000 | 1.000 | 1000 | 2000 | 1-2000 | 1 | pop-os | 64 | 0.3.5.9000 | `results/declcal_bnull_A2_res_1_2000.rds` | 0.18 MB | yes |
| A3 | 0.00000 | 1.000 | 1500 | 2000 | 1-2000 | 1 | pop-os | 64 | 0.3.5.9000 | `results/declcal_bnull_A3_res_1_2000.rds` | 0.18 MB | yes |
| C1 | 0.12418 | 1.500 | 1000 | 2000 | 1-2000 | 1 | pop-os | 64 | 0.3.5.9000 | `results/declcal_power_C1_res_1_2000.rds` | 0.17 MB | yes |
| C2 | 0.12418 | 1.500 | 1500 | 2000 | 1-2000 | 1 | pop-os | 64 | 0.3.5.9000 | `results/declcal_power_C2_res_1_2000.rds` | 0.17 MB | yes |
| C3 | 0.12418 | 2.000 | 1000 | 2000 | 1-2000 | 1 | pop-os | 64 | 0.3.5.9000 | `results/declcal_power_C3_res_1_2000.rds` | 0.17 MB | yes |
| C4 | 0.12418 | 2.000 | 1500 | 2000 | 1-2000 | 1 | pop-os | 64 | 0.3.5.9000 | `results/declcal_power_C4_res_1_2000.rds` | 0.17 MB | yes |

#### `declcalc0` — 10 cells (no combined bundles: one batch bundle per cell-run)

| cell | prevalence (super-population) | HR | n | rows per run | sim_id | runs (batch bundles) | host | workers | forestsearch | first batch bundle | total size | tracked (all) |
|---|---|---|---|---|---|---|---|---|---|---|---|---|
| B1 | 0.00000 | 0.657 | 500 | 2000 | 1-2000 | 1 | pop-os | 64 | 0.3.5.9000 | `results/declcalc0_inull_B1_res_1_2000.rds` | 0.53 MB | yes |
| B2 | 0.00000 | 0.657 | 1000 | 2000 | 1-2000 | 1 | pop-os | 64 | 0.3.5.9000 | `results/declcalc0_inull_B2_res_1_2000.rds` | 0.53 MB | yes |
| B3 | 0.00000 | 0.657 | 1500 | 2000 | 1-2000 | 1 | pop-os | 64 | 0.3.5.9000 | `results/declcalc0_inull_B3_res_1_2000.rds` | 0.53 MB | yes |
| B4 | 0.00000 | 0.721 | 500 | 2000 | 1-2000 | 1 | pop-os | 64 | 0.3.5.9000 | `results/declcalc0_inull_B4_res_1_2000.rds` | 0.54 MB | yes |
| B5 | 0.00000 | 0.721 | 1000 | 2000 | 1-2000 | 1 | pop-os | 64 | 0.3.5.9000 | `results/declcalc0_inull_B5_res_1_2000.rds` | 0.53 MB | yes |
| B6 | 0.00000 | 0.721 | 1500 | 2000 | 1-2000 | 1 | pop-os | 64 | 0.3.5.9000 | `results/declcalc0_inull_B6_res_1_2000.rds` | 0.53 MB | yes |
| C1 | 0.12418 | 1.500 | 1000 | 2000 | 1-2000 | 1 | pop-os | 64 | 0.3.5.9000 | `results/declcalc0_power_C1_res_1_2000.rds` | 0.54 MB | yes |
| C2 | 0.12418 | 1.500 | 1500 | 2000 | 1-2000 | 1 | pop-os | 64 | 0.3.5.9000 | `results/declcalc0_power_C2_res_1_2000.rds` | 0.54 MB | yes |
| C3 | 0.12418 | 2.000 | 1000 | 2000 | 1-2000 | 1 | pop-os | 64 | 0.3.5.9000 | `results/declcalc0_power_C3_res_1_2000.rds` | 0.55 MB | yes |
| C4 | 0.12418 | 2.000 | 1500 | 2000 | 1-2000 | 1 | pop-os | 64 | 0.3.5.9000 | `results/declcalc0_power_C4_res_1_2000.rds` | 0.55 MB | yes |

#### `mrs5` — 18 cells (no combined bundles: one batch bundle per cell-run)

| cell | prevalence (super-population) | HR | n | rows per run | sim_id | runs (batch bundles) | host | workers | forestsearch | first batch bundle | total size | tracked (all) |
|---|---|---|---|---|---|---|---|---|---|---|---|---|
| — | 0.12418 | 1.00 | 500 | 200 | 1-200 | 1 | pop-os | 64 | 0.3.5.9000 | `results/fs_effMaxSG_fb_mr_field_m1_h100_knoise0_n500_nb20_mrs5probe_res_1_200.rds` | 0.11 MB | yes |
| — | 0.12418 | 1.00 | 1000 | 200 | 1-200 | 1 | pop-os | 64 | 0.3.5.9000 | `results/fs_effMaxSG_fb_mr_field_m1_h100_knoise0_n1000_nb20_mrs5sweep_res_1_200.rds` | 0.12 MB | yes |
| — | 0.12418 | 1.00 | 1500 | 200 | 1-200 | 1 | pop-os | 64 | 0.3.5.9000 | `results/fs_effMaxSG_fb_mr_field_m1_h100_knoise0_n1500_nb20_mrs5sweep_res_1_200.rds` | 0.12 MB | yes |
| — | 0.12418 | 1.50 | 500 | 200 | 1-200 | 1 | pop-os | 64 | 0.3.5.9000 | `results/fs_effMaxSG_fb_mr_field_m1_h150_knoise0_n500_nb20_mrs5sweep_res_1_200.rds` | 0.15 MB | yes |
| — | 0.12418 | 1.50 | 1000 | 200 | 1-200 | 1 | pop-os | 64 | 0.3.5.9000 | `results/fs_effMaxSG_fb_mr_field_m1_h150_knoise0_n1000_nb20_mrs5sweep_res_1_200.rds` | 0.15 MB | yes |
| — | 0.12418 | 1.50 | 1500 | 200 | 1-200 | 1 | pop-os | 64 | 0.3.5.9000 | `results/fs_effMaxSG_fb_mr_field_m1_h150_knoise0_n1500_nb20_mrs5sweep_res_1_200.rds` | 0.15 MB | yes |
| — | 0.12418 | 1.75 | 500 | 200 | 1-200 | 1 | pop-os | 64 | 0.3.5.9000 | `results/fs_effMaxSG_fb_mr_field_m1_h175_knoise0_n500_nb20_mrs5sweep_res_1_200.rds` | 0.15 MB | yes |
| — | 0.12418 | 1.75 | 1000 | 200 | 1-200 | 1 | pop-os | 64 | 0.3.5.9000 | `results/fs_effMaxSG_fb_mr_field_m1_h175_knoise0_n1000_nb20_mrs5sweep_res_1_200.rds` | 0.16 MB | yes |
| — | 0.12418 | 1.75 | 1500 | 200 | 1-200 | 1 | pop-os | 64 | 0.3.5.9000 | `results/fs_effMaxSG_fb_mr_field_m1_h175_knoise0_n1500_nb20_mrs5sweep_res_1_200.rds` | 0.15 MB | yes |
| — | 0.30655 | 1.00 | 500 | 200 | 1-200 | 1 | pop-os | 64 | 0.3.5.9000 | `results/fs_effMaxSG_fb_mr_field_m1_h100_knoise0_n500_z1q60_nb20_mrs5sweep_res_1_200.rds` | 0.15 MB | yes |
| — | 0.30655 | 1.00 | 1000 | 200 | 1-200 | 1 | pop-os | 64 | 0.3.5.9000 | `results/fs_effMaxSG_fb_mr_field_m1_h100_knoise0_n1000_z1q60_nb20_mrs5sweep_res_1_200.rds` | 0.15 MB | yes |
| — | 0.30655 | 1.00 | 1500 | 200 | 1-200 | 1 | pop-os | 64 | 0.3.5.9000 | `results/fs_effMaxSG_fb_mr_field_m1_h100_knoise0_n1500_z1q60_nb20_mrs5sweep_res_1_200.rds` | 0.16 MB | yes |
| — | 0.30655 | 1.50 | 500 | 200 | 1-200 | 1 | pop-os | 64 | 0.3.5.9000 | `results/fs_effMaxSG_fb_mr_field_m1_h150_knoise0_n500_z1q60_nb20_mrs5sweep_res_1_200.rds` | 0.16 MB | yes |
| — | 0.30655 | 1.50 | 1000 | 200 | 1-200 | 1 | pop-os | 64 | 0.3.5.9000 | `results/fs_effMaxSG_fb_mr_field_m1_h150_knoise0_n1000_z1q60_nb20_mrs5sweep_res_1_200.rds` | 0.16 MB | yes |
| — | 0.30655 | 1.50 | 1500 | 200 | 1-200 | 1 | pop-os | 64 | 0.3.5.9000 | `results/fs_effMaxSG_fb_mr_field_m1_h150_knoise0_n1500_z1q60_nb20_mrs5sweep_res_1_200.rds` | 0.15 MB | yes |
| — | 0.30655 | 1.75 | 500 | 200 | 1-200 | 1 | pop-os | 64 | 0.3.5.9000 | `results/fs_effMaxSG_fb_mr_field_m1_h175_knoise0_n500_z1q60_nb20_mrs5sweep_res_1_200.rds` | 0.16 MB | yes |
| — | 0.30655 | 1.75 | 1000 | 200 | 1-200 | 1 | pop-os | 64 | 0.3.5.9000 | `results/fs_effMaxSG_fb_mr_field_m1_h175_knoise0_n1000_z1q60_nb20_mrs5sweep_res_1_200.rds` | 0.15 MB | yes |
| — | 0.30655 | 1.75 | 1500 | 200 | 1-200 | 1 | pop-os | 64 | 0.3.5.9000 | `results/fs_effMaxSG_fb_mr_field_m1_h175_knoise0_n1500_z1q60_nb20_mrs5sweep_res_1_200.rds` | 0.15 MB | yes |

#### `s5rerun` — 18 cells

| cell | prevalence (super-population) | HR | n | rows | sim_id | batches | host | workers | forestsearch | combined bundle | size | tracked |
|---|---|---|---|---|---|---|---|---|---|---|---|---|
| — | 0.12418 | 1.00 | 500 | 2000 | 1-2000 | 2 | Mac-Studio-3.local | 13 | 0.3.5.9000 | `results/fs_effMaxSG_fb_mr_field_m1_h100_knoise0_n500_nb20_s5rerun_combined_1_2000.rds` | 1.16 MB | yes |
| — | 0.12418 | 1.00 | 1000 | 2000 | 1-2000 | 2 | Mac-Studio-3.local | 13 | 0.3.5.9000 | `results/fs_effMaxSG_fb_mr_field_m1_h100_knoise0_n1000_nb20_s5rerun_combined_1_2000.rds` | 1.13 MB | yes |
| — | 0.12418 | 1.00 | 1500 | 2000 | 1-2000 | 2 | Mac-Studio-3.local | 13 | 0.3.5.9000 | `results/fs_effMaxSG_fb_mr_field_m1_h100_knoise0_n1500_nb20_s5rerun_combined_1_2000.rds` | 1.08 MB | yes |
| — | 0.12418 | 1.50 | 500 | 2000 | 1-2000 | 2 | Mac-Studio-3.local | 13 | 0.3.5.9000 | `results/fs_effMaxSG_fb_mr_field_m1_h150_knoise0_n500_nb20_s5rerun_combined_1_2000.rds` | 1.43 MB | yes |
| — | 0.12418 | 1.50 | 1000 | 2000 | 1-2000 | 2 | Mac-Studio-3.local | 13 | 0.3.5.9000 | `results/fs_effMaxSG_fb_mr_field_m1_h150_knoise0_n1000_nb20_s5rerun_combined_1_2000.rds` | 1.48 MB | yes |
| — | 0.12418 | 1.50 | 1500 | 2000 | 1-2000 | 2 | Mac-Studio-3.local | 13 | 0.3.5.9000 | `results/fs_effMaxSG_fb_mr_field_m1_h150_knoise0_n1500_nb20_s5rerun_combined_1_2000.rds` | 1.48 MB | yes |
| — | 0.12418 | 1.75 | 500 | 2000 | 1-2000 | 2 | Mac-Studio-3.local | 13 | 0.3.5.9000 | `results/fs_effMaxSG_fb_mr_field_m1_h175_knoise0_n500_nb20_s5rerun_combined_1_2000.rds` | 1.46 MB | yes |
| — | 0.12418 | 1.75 | 1000 | 2000 | 1-2000 | 2 | Mac-Studio-3.local | 13 | 0.3.5.9000 | `results/fs_effMaxSG_fb_mr_field_m1_h175_knoise0_n1000_nb20_s5rerun_combined_1_2000.rds` | 1.49 MB | yes |
| — | 0.12418 | 1.75 | 1500 | 2000 | 1-2000 | 2 | Mac-Studio-3.local | 13 | 0.3.5.9000 | `results/fs_effMaxSG_fb_mr_field_m1_h175_knoise0_n1500_nb20_s5rerun_combined_1_2000.rds` | 1.47 MB | yes |
| — | 0.30655 | 1.00 | 500 | 2000 | 1-2000 | 2 | Mac-Studio-3.local | 13 | 0.3.5.9000 | `results/fs_effMaxSG_fb_mr_field_m1_h100_knoise0_n500_z1q60_nb20_s5rerun_combined_1_2000.rds` | 1.45 MB | yes |
| — | 0.30655 | 1.00 | 1000 | 2000 | 1-2000 | 2 | Mac-Studio-3.local | 13 | 0.3.5.9000 | `results/fs_effMaxSG_fb_mr_field_m1_h100_knoise0_n1000_z1q60_nb20_s5rerun_combined_1_2000.rds` | 1.48 MB | yes |
| — | 0.30655 | 1.00 | 1500 | 2000 | 1-2000 | 2 | Mac-Studio-3.local | 13 | 0.3.5.9000 | `results/fs_effMaxSG_fb_mr_field_m1_h100_knoise0_n1500_z1q60_nb20_s5rerun_combined_1_2000.rds` | 1.48 MB | yes |
| — | 0.30655 | 1.50 | 500 | 2000 | 1-2000 | 2 | Mac-Studio-3.local | 13 | 0.3.5.9000 | `results/fs_effMaxSG_fb_mr_field_m1_h150_knoise0_n500_z1q60_nb20_s5rerun_combined_1_2000.rds` | 1.50 MB | yes |
| — | 0.30655 | 1.50 | 1000 | 2000 | 1-2000 | 2 | Mac-Studio-3.local | 13 | 0.3.5.9000 | `results/fs_effMaxSG_fb_mr_field_m1_h150_knoise0_n1000_z1q60_nb20_s5rerun_combined_1_2000.rds` | 1.49 MB | yes |
| — | 0.30655 | 1.50 | 1500 | 2000 | 1-2000 | 2 | Mac-Studio-3.local | 13 | 0.3.5.9000 | `results/fs_effMaxSG_fb_mr_field_m1_h150_knoise0_n1500_z1q60_nb20_s5rerun_combined_1_2000.rds` | 1.47 MB | yes |
| — | 0.30655 | 1.75 | 500 | 2000 | 1-2000 | 2 | Mac-Studio-3.local | 13 | 0.3.5.9000 | `results/fs_effMaxSG_fb_mr_field_m1_h175_knoise0_n500_z1q60_nb20_s5rerun_combined_1_2000.rds` | 1.49 MB | yes |
| — | 0.30655 | 1.75 | 1000 | 2000 | 1-2000 | 2 | Mac-Studio-3.local | 13 | 0.3.5.9000 | `results/fs_effMaxSG_fb_mr_field_m1_h175_knoise0_n1000_z1q60_nb20_s5rerun_combined_1_2000.rds` | 1.48 MB | yes |
| — | 0.30655 | 1.75 | 1500 | 2000 | 1-2000 | 2 | Mac-Studio-3.local | 13 | 0.3.5.9000 | `results/fs_effMaxSG_fb_mr_field_m1_h175_knoise0_n1500_z1q60_nb20_s5rerun_combined_1_2000.rds` | 1.46 MB | yes |

- `seed_base` in every meta above (combined metas; the first batch meta per `idsweep` cell): 8316951 (per replicate `seed_base + sim_id`).

### 3.3 Git

- `dinamr` bundles/renders: 3 commits; first `a462f401`; last `322daebd`.
- `grfmr` bundles/renders: 3 commits; first `6765c372`; last `4e21ea2c`.
- `p12x20` bundles/renders: 13 commits; first `118a66ce`; last `c70b90d6`.
- `idsweep` bundles/renders: 1 commits; first `d62e1391`; last `d62e1391`.
- `nullid` bundles/renders: 6 commits; first `0393f76b`; last `89c2e6f0`.
- `nullc125` bundles/renders: 7 commits; first `f7bbfa40`; last `6ee4a45d`.
- `nullmr` bundles/renders: 7 commits; first `dbf210dc`; last `2a08879d`.
- `declcal` bundles/renders: 5 commits; first `f9cb7e0f`; last `e9de87c7`.
- `declcalc0` bundles/renders: 5 commits; first `dbc14acb`; last `8ad21cf5`.
- `mrs5` bundles/renders: 2 commits; first `d637ff07`; last `7dd22c9e`.
- `s5rerun` bundles/renders: 1 commits; first `5fec9198`; last `5fec9198`.
- `campaign/p12x20` tip `c6d9c82a`; ancestor of HEAD: yes.

### 3.4 Campaign tags in `results/` (last token of each bundle stem)

| tag | combined | batch |
|---|---|---|
| `A1` | 0 | 1 |
| `A2` | 0 | 2 |
| `A3` | 0 | 1 |
| `B1` | 0 | 2 |
| `B2` | 0 | 2 |
| `B3` | 0 | 2 |
| `B4` | 0 | 2 |
| `B5` | 0 | 3 |
| `B6` | 0 | 2 |
| `banddial` | 6 | 12 |
| `bdinert` | 0 | 1 |
| `bdsmoke` | 0 | 6 |
| `burst100` | 0 | 1 |
| `burst60` | 0 | 1 |
| `C1` | 0 | 2 |
| `C2` | 0 | 2 |
| `C3` | 0 | 2 |
| `C4` | 0 | 2 |
| `cert20` | 7 | 14 |
| `cert20smoke` | 0 | 2 |
| `dinamr` | 18 | 36 |
| `dinamrprobe` | 0 | 10 |
| `dinamrsmk` | 0 | 2 |
| `e0stud` | 0 | 1 |
| `e1inert` | 0 | 1 |
| `e1regr` | 0 | 1 |
| `e1scale` | 0 | 1 |
| `e1stud` | 6 | 12 |
| `explicit` | 0 | 1 |
| `field` | 0 | 1 |
| `grfmr` | 18 | 36 |
| `grfmrsmk` | 0 | 1 |
| `grfprobe` | 0 | 5 |
| `h6smoke` | 0 | 2 |
| `idsweep` | 0 | 288 |
| `ij` | 0 | 1 |
| `map1` | 5 | 10 |
| `map1c` | 5 | 10 |
| `map1smoke` | 0 | 5 |
| `map1w` | 5 | 10 |
| `methknob` | 0 | 1 |
| `methknobpre` | 0 | 1 |
| `mrs5pre` | 0 | 3 |
| `mrs5probe` | 0 | 2 |
| `mrs5sweep` | 0 | 17 |
| `n1000` | 2 | 10 |
| `n1500` | 1 | 3 |
| `n3000` | 0 | 3 |
| `n500` | 4 | 17 |
| `n700` | 1 | 4 |
| `nb10smoke` | 0 | 2 |
| `nb20j20smoke` | 0 | 5 |
| `nb20smoke` | 0 | 2 |
| `nbinert` | 0 | 1 |
| `nullc125` | 0 | 18 |
| `nullid` | 0 | 18 |
| `nullmr` | 0 | 18 |
| `off` | 0 | 1 |
| `old` | 0 | 1 |
| `on` | 0 | 2 |
| `p12ext` | 5 | 10 |
| `p12extsmoke` | 0 | 2 |
| `p30` | 4 | 8 |
| `p30sg` | 4 | 8 |
| `p30sgnb20` | 2 | 4 |
| `p30sgnb20j20` | 5 | 10 |
| `p30sgsmoke` | 0 | 4 |
| `p30smoke` | 0 | 4 |
| `pBoc` | 0 | 16 |
| `postmerge` | 0 | 1 |
| `quickrun` | 0 | 32 |
| `s5rerun` | 18 | 36 |
| `s5rerunchk` | 0 | 1 |
| `s5smk1500` | 0 | 1 |
| `s7` | 2 | 4 |
| `s7c` | 2 | 4 |
| `s7csmoke` | 0 | 2 |
| `s7u` | 2 | 2 |
| `s7w` | 2 | 4 |
| `s7wsmoke` | 0 | 2 |
| `sginert` | 0 | 1 |
| `smoke` | 0 | 2 |
| `stud1decomp` | 0 | 1 |
| `stud1inert` | 0 | 1 |
| `t2grf` | 0 | 1 |
| `t2post` | 0 | 1 |
| `t2pre` | 0 | 1 |
| `t3dina` | 0 | 1 |
| `t3dinaoff` | 0 | 1 |
| `t3grf` | 0 | 1 |
| `t3grfoff` | 0 | 1 |
| `t3mroff` | 0 | 1 |
| `t3post` | 0 | 1 |
| `t3pre` | 0 | 1 |
| `tier2` | 4 | 8 |
| `tier2probe` | 0 | 4 |
| `tier2smoke` | 0 | 4 |
| `uburst` | 0 | 2 |
| `unset` | 0 | 1 |
| `usmoke` | 0 | 2 |
| `z1qinert` | 0 | 1 |

- `p12x20_2026-09-12/`: 9 combined, 18 batch (tag `p12x20`).

### 3.5 Payload inventory table

| path pattern (first match wins) | tracked/disk | total | largest single file | what it is |
|---|---|---|---|---|
| `results/*dinamr*.rds` | 66/66 | 50.54 MB | `dina_effMaxSG_fb_mr_field_m1_h150_knoise0_n500_z1q60_nb20_dinamr_combined_1_2000.rds` 1.54 MB | `dinamr` per-replicate bundles + metas (batch and combined) |
| `results/*grfmr*.rds` | 55/55 | 55.17 MB | `grf_effMaxSG_fb_mr_field_m1_h100_knoise0_n1000_z1q60_nb20_grfmr_combined_1_2000.rds` 1.55 MB | `grfmr` per-replicate bundles + metas (batch and combined), and the `grfmrsmk` Stage 1 smoke |
| `results/*grfprobe*.rds` | 5/5 | 155 KB | `grf_effMaxSG_fb_mr_field_m1_h150_knoise0_n500_nb20_grfprobe_res_1_36.rds` 31 KB | `grfprobe` cost probes, 36 replicates each |
| `results/*_nomr_idsweep_*.rds` | 288/288 | 16.92 MB | `grf_effMaxSG_fb_mr_field_m1_h100_knoise0_n500_z1q60_nb20_nomr_idsweep_res_1_500.rds` 69 KB | `idsweep` per-replicate bundles (MR off, 500 replicates, one batch per run; all three engines) |
| `results/*_nomr_nullid_*.rds` | 18/18 | 3.49 MB | `grf_effMaxSG_fb_mr_field_m1_h072_knoise0_n500_null721_nb20_nomr_nullid_res_1_2000.rds` 283 KB | `nullid` per-replicate bundles (structural null, MR off, 2,000 replicates, one batch per run; all three engines) |
| `results/*_nomr_c125c100_nullc125_*.rds` | 18/18 | 2.05 MB | `grf_effMaxSG_fb_mr_field_m1_h072_knoise0_n500_null721_nb20_nomr_c125c100_nullc125_res_1_2000.rds` 282 KB | `nullc125` per-replicate bundles (structural null at c1 1.25 / c2 1.00, MR off, 2,000 replicates, one batch per run; all three engines) |
| `results/*_nullc125*_quickrun_*.rds` | 12/12 | 54 KB | `grf_effMaxSG_fb_mr_field_m1_h066_knoise0_n500_null657_nb20_nomr_nullc125inertunset_quickrun_res_1_20.rds` 6 KB | `nullc125` Step 3.1 smoke (`nullc125smoke`, at 1.25 / 1.00) and the Step 1.5 threshold-knob inertness renders (`nullc125inert*`, at 0.90 / 0.80), 20 replicates each |
| `results/*_nb20_nullmr_*.rds` | 18/18 | 17.61 MB | `grf_effMaxSG_fb_mr_field_m1_h072_knoise0_n500_null721_nb20_nullmr_res_1_2000.rds` 1.48 MB | `nullmr` per-replicate bundles (structural null at c1 0.90 / c2 0.80, MR on, 2,000 replicates, one batch per run; all three engines) |
| `results/*_nullmrsmoke_quickrun_*.rds` | 6/6 | 78 KB | `grf_effMaxSG_fb_mr_field_m1_h066_knoise0_n500_null657_nb20_nullmrsmoke_quickrun_res_1_20.rds` 18 KB | `nullmr` Step 3.1 smoke (`nullmrsmoke`, MR on), 20 replicates each |
| `results/declcalc0_smoke_*.rds` | 1/1 | 3 KB | `declcalc0_smoke_B5_res_1_5.rds` 3 KB | `declcalc0` Stage 1 smoke (cell B5, 5 replicates) |
| `results/declcalc0_*.rds` | 10/10 | 5.37 MB | `declcalc0_power_C3_res_1_2000.rds` 560 KB | `declcalc0` per-replicate payloads (the `declcal` B and C blocks re-run with `declaration_c0` = 0.70 / 0.75 / 0.80 / 0.85; `declcal` schema + per-c0 columns + aux + meta; 2,000 replicates per cell) |
| `results/declcal_c0approx_*.rds` | 1/1 | 30 KB | `declcal_c0approx_res.rds` 30 KB | `declcal` c0 approximate table (120 field captures, B 2000; plug-in fixed-cutoff rates) |
| `results/declcal_pilot_*.rds` | 1/1 | 27 KB | `declcal_pilot_A2_res_1_200.rds` 27 KB | `declcal` Stage 1 pilot (cell A2, 200 replicates, B 2000 sub-sampled) |
| `results/declcal_*.rds` | 13/13 | 2.22 MB | `declcal_bnull_A1_res_1_2000.rds` 182 KB | `declcal` per-replicate payloads (section-5 schema + aux + meta; FS only, c1 = c2 = 1.0, 2,000 replicates per cell; blocks bnull / inull / power) |
| `results/*null*_quickrun_*.rds` | 4/4 | 20 KB | `fs_effMaxSG_fb_mr_field_m1_h150_knoise0_n500_nb20_nomr_nullinert_quickrun_res_1_20.rds` 7 KB | `nullid` Step 2 smoke (`nullsmk`) and the alt-path inertness check (`nullinert`), 20 replicates each |
| `results/*_mrs5probe_*.rds` | 2/2 | 125 KB | `fs_effMaxSG_fb_mr_field_m1_h100_knoise0_n500_nb20_mrs5probe_res_1_200.rds` 117 KB | `mrs5` probe: A7 after arm (200 replicates) and its Gate T (10) |
| `results/*_mrs5sweep_*.rds` | 17/17 | 2.54 MB | `fs_effMaxSG_fb_mr_field_m1_h150_knoise0_n500_z1q60_nb20_mrs5sweep_res_1_200.rds` 162 KB | `mrs5` sweep: after arm, 17 Section 5 cells, 200 replicates each |
| `results/*_mrs5pre_*.rds` | 3/3 | 28 KB | `fs_effMaxSG_fb_mr_field_m1_h150_knoise0_n500_z1q60_nb20_mrs5pre_res_1_10.rds` 11 KB | `mrs5` parent-build (`ba595f4b`) checks, 10 replicates: A7, cert20 HR 1.00 n 500, e1stud HR 1.50 n 500 |
| `results/*_s5rerun_*.rds` | 54/54 | 51.26 MB | `fs_effMaxSG_fb_mr_field_m1_h150_knoise0_n500_z1q60_nb20_s5rerun_combined_1_2000.rds` 1.50 MB | `s5rerun`: the 18 Section 5 FS cells re-run under the aligned package, 2,000 replicates each (batch and combined) |
| `results/*_s5rerunchk_*.rds` | 1/1 | 117 KB | `fs_effMaxSG_fb_mr_field_m1_h100_knoise0_n500_nb20_s5rerunchk_res_1_200.rds` 117 KB | `s5rerun` Step 2 check: A7, 200 replicates |
| `results/*_s5smk1500_*.rds` | 1/1 | 13 KB | `fs_effMaxSG_fb_mr_field_m1_h175_knoise0_n1500_z1q60_nb20_s5smk1500_res_1_13.rds` 13 KB | `s5rerun` n 1500 memory smoke: 31% HR 1.75 n 1500, 13 replicates |
| `results/fs_*.rds` | 324/324 | 149.18 MB | `fs_maxeffCons_fb_mr_field_m1_h150_knoise0_n1000_p12ext_combined_1_2000.rds` 1.51 MB | FS bundles -- the comparator grid plus every earlier FS campaign |
| `results/*.rds` | 28/28 | 1.02 MB | `grf_eff_fb_mr_m1_h10_knoise0_n500_combined_1_500.rds` 150 KB | other bundles in `results/` |
| `p12x20_2026-09-12/*_res_*.rds` | 18/18 | 11.88 MB | `fs_effMaxSG_fb_mr_field_m1_h175_knoise0_n1000_nb20_p12x20_res_1001_2000.rds` 745 KB | `p12x20` per-replicate batch bundles + metas (campaign directory, not `results/`) |
| `p12x20_2026-09-12/*_combined_*.rds` | 9/9 | 11.75 MB | `fs_effMaxSG_fb_mr_field_m1_h175_knoise0_n1000_nb20_p12x20_combined_1_2000.rds` 1.44 MB | `p12x20` combined bundles (campaign directory) |
| `p12x20_2026-09-12/*.html` | 27/27 | 112.16 MB | `p12x20_A4_h175_n500_combine_1.html` 4.18 MB | `p12x20` batch and combine renders (campaign directory, not the root) |
| `p12x20_2026-09-12/GATE2_*.txt` | 9/9 | 67 KB | `GATE2_p12x20_A5_2026-09-12.txt` 7 KB | `p12x20` per-cell Gate 2 records |
| `p12x20_2026-09-12/REPORT_*.md` | 9/9 | 87 KB | `REPORT_p12x20_A5_2026-09-12.md` 10 KB | `p12x20` per-cell reports |
| `scripts_p12x20/logs/*` | 56/56 | 104 KB | `p12x20_A2_h150_n1000_batch_1001.log` 4 KB | `p12x20` runner, driver and per-render logs -- `WALL_SECONDS` / `CELL DONE wall=` |
| `scripts_p12x20/*` | 4/4 | 33 KB | `gate2F.R` 15 KB | `p12x20` runner, driver, Gate 2 checker, STATUS generator |
| `STATUS_p12x20.md` | 1/1 | 15 KB | `STATUS_p12x20.md` 15 KB | `p12x20` campaign-scoped record (no pin claim) |
| `LOG_p12x20_progress.txt` | 1/1 | 1 KB | `LOG_p12x20_progress.txt` 1 KB | `p12x20` per-cell heartbeat |
| `mrs5probe/**` | 7/7 | 17 KB | `mrs5probe_A7_gateT_batch_1.log` 3 KB | `mrs5` probe runner, paired read-out, logs (`WALL_SECONDS`, worker build checks) |
| `mrs5sweep/**` | 60/60 | 141 KB | `sweep_driver.log` 24 KB | `mrs5` sweep driver, runner, paired read-out, cell list, logs (`WALL_SECONDS`, worker build checks) |
| `mrs5pre/**` | 4/4 | 7 KB | `mrs5pre_C31_h100_n500_gateP_batch_1.log` 4 KB | `mrs5` parent-build check logs |
| `s5rerun/**` | 151/151 | 362 KB | `s5rerun_mem.log` 80 KB | `s5rerun` driver, runner, recorder, paired read-out, ranges, logs (`WALL_SECONDS`, `CELL DONE wall=`, worker build checks, memory samples) |
| `mr_sweep/**` | 210/210 | 15.19 MB | `grf_mr_n500_res.rds` 130 KB | `mr_sweep/` -- an earlier seed-table sweep, superseded, kept for provenance |
| `scripts_dinamr/logs/*` | 937/938 | 3.68 MB | `idsweep.driver.part2.log` 203 KB | per-render, driver and gate logs -- `WALL_SECONDS` / `CELL DONE wall=` |
| `scripts_dinamr/*.R` | 56/56 | 505 KB | `declcalc0_run.R` 30 KB | drivers, checkers, projections, extractions (R) |
| `scripts_dinamr/*.sh` | 21/21 | 73 KB | `nullmr.sh` 9 KB | render/campaign drivers and the closeout checker (shell) |
| `scripts_dinamr/*.py` | 2/2 | 13 KB | `transplant_grfmr.py` 12 KB | transplant / chunk-diff helpers (Python) |
| `scripts_dinamr/*.cells` | 20/20 | 4 KB | `idsweep.cells` 0 KB | cell lists, one line per cell |
| `scripts_dinamr/resume/*.cells` | 2/2 | 1 KB | `declcalc0_inull.cells` 0 KB | `declcalc0` Stage 2 resume cell lists (same basenames as the block files, so the campaign tags are unchanged; the cells not completed by the stopped run) |
| `scripts_dinamr/*.rds` | 19/19 | 156 KB | `grfmr_tables.rds` 62 KB | saved derived objects (projections, walls, extracted tables) |
| `scripts_dinamr/*.md` | 1/1 | 10 KB | `README.md` 10 KB | `README.md` -- the standing rules, and what each script is |
| `scripts_dinamr/*.txt` | 1/1 | 5 KB | `grf_mechanism_output.txt` 5 KB | captured script output (GRF mechanism probe) |
| `mrs5*_*.html` | 22/22 | 93.21 MB | `mrs5sweep_P31_h100_n1000_batch_1.html` 4.28 MB | `mrs5` probe, sweep and parent-build check renders |
| `s5rerun*_*.html` | 55/55 | 248.33 MB | `s5rerun_P31_h100_n500_combine_1.html` 4.54 MB | `s5rerun` batch and combine renders, and the Step 2 check render |
| `s5smk1500_*.html` | 1/1 | 4.44 MB | `s5smk1500_P31_h175_n1500_batch_1.html` 4.44 MB | `s5rerun` n 1500 memory-smoke render |
| `dinamr_*.html` | 54/54 | 235.69 MB | `dinamr_C31_h100_n500_combine_1.html` 4.39 MB | `dinamr` batch and combine renders |
| `grfmr_*.html` | 54/54 | 236.03 MB | `grfmr_C124_h100_n1500_batch_1001.html` 4.40 MB | `grfmr` batch and combine renders |
| `grfprobe_*.html` | 5/5 | 21.56 MB | `grfprobe_g_p124_h150_n1500.html` 4.33 MB | `grfprobe` renders |
| `idsweep_*.html` | 288/288 | 1089.06 MB | `idsweep_p124_h100_n1500_dina_minSG.html` 3.81 MB | `idsweep` batch renders, one per cell-run |
| `nullid_*.html` | 18/18 | 69.75 MB | `nullid_null0721_n1500_grf_effMaxSG.html` 3.89 MB | `nullid` batch renders, one per cell-run |
| `nullsmk_*.html` | 3/3 | 11.48 MB | `nullsmk_null0657_n500_grf_effMaxSG.html` 3.85 MB | `nullid` Step 2 smoke renders |
| `nullinert_*.html` | 1/1 | 3.86 MB | `nullinert_alt_h150_n500_consistency_effMaxSG.html` 3.86 MB | the `nullid` alt-path inertness-check render |
| `nullc125_*.html` | 18/18 | 66.22 MB | `nullc125_null0721_n1000_grf_effMaxSG.html` 3.70 MB | `nullc125` batch renders, one per cell-run |
| `nullc125smoke_*.html` | 3/3 | 10.83 MB | `nullc125smoke_null0657_n500_grf_effMaxSG.html` 3.63 MB | `nullc125` Step 3.1 smoke renders |
| `nullmr_*.html` | 18/18 | 76.93 MB | `nullmr_null0657_n1500_consistency_effMaxSG.html` 4.30 MB | `nullmr` batch renders, one per cell-run |
| `nullmrsmoke_*.html` | 6/6 | 25.25 MB | `nullmrsmoke_null0657_n500_grf_effMaxSG.html` 4.24 MB | `nullmr` Step 3.1 smoke renders |
| `nullc125inert*_*.html` | 9/9 | 32.70 MB | `nullc125inertunset_grf.html` 3.67 MB | the `nullc125` threshold-knob inertness renders (pre-edit, unset, explicit) |
| `probe_*.html` | 10/10 | 43.14 MB | `probe_p31_h100_n500.html` 4.33 MB | Gate 1 cost-probe renders (`dinamr` era) |
| `summary_*.html` | 15/15 | 55.85 MB | `summary_grfmr.html` 7.87 MB | summary rendered outputs, all campaigns |
| `summary_*.qmd` | 15/15 | 398 KB | `summary_grfmr.qmd` 93 KB | summary sources, all campaigns |
| `sim_fs_maxeffCons_fb_mr_field_m1_template.qmd` | 1/1 | 182 KB | `sim_fs_maxeffCons_fb_mr_field_m1_template.qmd` 182 KB | **the** template `dinamr` / `grfmr` / the FS grid all render |
| `sim_*.qmd` | 53/53 | 4.19 MB | `sim_fs_maxeffCons_fb_mr_m1_h10_knoise0_n500_batch_1_100.qmd` 98 KB | other simulation templates (earlier campaigns and variants) |
| `sim_*.html` | 52/52 | 150.72 MB | `sim_fs_maxeffCons_fb_mr_m1_h10_knoise0_n500_batch_1_1000.html` 3.33 MB | renders of those other templates |
| `fs_*.html` | 245/245 | 973.62 MB | `fs_maxeffCons_fb_mr_field_m1_h175_knoise0_n1000_tier2_combine_1_2000.html` 4.34 MB | FS campaign batch/combine renders (`p12ext`, `tier2`, `e1stud`, `cert20`, earlier) |
| `*.html` | 53/53 | 180.74 MB | `t3gate_t3grf.html` 4.31 MB | remaining renders (smoke, gate, dflt, compare) |
| `HALT_*.txt` | 2/2 | 4 KB | `HALT_nullid_null0657_n1500_2026-09-21.txt` 2 KB | halt records (a cell abandoned mid-campaign) |
| `REPORT_*.md` | 74/74 | 1.32 MB | `REPORT_fixedphat_ij2s_2026-09-09.md` 79 KB | REPORT documents |
| `TABLES_*.md` | 2/2 | 83 KB | `TABLES_grfmr_completion_2026-09-12.md` 53 KB | TABLES documents |
| `REVIEW_*.md` | 3/3 | 30 KB | `REVIEW_dinamr_blockC_2026-09-11.md` 13 KB | REVIEW documents |
| `current_status.md` | 1/1 | 101 KB | `current_status.md` 101 KB | this file -- the directory's catalog at a pin |
| `*.md` | 2/2 | 54 KB | `status_curated.md` 52 KB | other notes in the directory |
| `*.qmd` | 21/21 | 1.44 MB | `gate_d2_cim_unset.qmd` 156 KB | remaining `.qmd` |
| `*.R` | 4/4 | 63 KB | `p12ext_findings.R` 24 KB | top-level ad-hoc R scripts |
| `**` | 3/6 | 254 KB | `sim_fs_maxeffCons_fb_mr_m1_h10_knoise0_n1000_batch_1_200.rmarkdown` 80 KB | everything else |
| **total** | **3682/3686** | **4152 MB** | `summary_grfmr.html` 7.87 MB | every file, each counted once |

FILES OVER 50 MB: 0 ; OVER 100 MB: 0
UNTRACKED:
  maxeffCons_mr_coverage_sweep_h10_knoise0.rmarkdown
  scripts_dinamr/logs/nullmr_findings.err
  sim_fs_maxeffCons_fb_mr_m1_h10_knoise0_n1000_batch_1_200.rmarkdown
  summary_complement_variance_files/figure-commonmark/a3-plot-1.png

Sizes are **apparent size** (`st_size`), in MiB/KiB, not disk usage; `du` reports block-allocated size and reads larger for many small files. **Every file is counted exactly once**: the rules are applied first-match-wins and the rows sum to the total. **Files over 50 MB: 0; over 100 MB: 0.** The gitignored `_gateT_pre_template_files/` and `.DS_Store` are excluded throughout. The `current_status.md` row shows this file's size at the pin, before this regeneration.

**Where to start, by question**

| If you need | Read |
|---|---|
| Per-cell coverage, bias, SDs, misses — DINA | `summary_dinamr.html`, or the Block reports |
| Per-cell numbers — GRF, all 18 cells | `TABLES_grfmr_completion_2026-09-12.md`, `summary_grfmr.html` |
| GRF at the HR 1.00 cells: selection rate and bound location, FS beside GRF | `REPORT_grfmr_completion_2026-09-12.md` |
| FS classification and bound location | `REPORT_fs_extraction_2026-09-11.md` |
| Why a quoted FS range differs from the certification record | `REPORT_fs_products_reconciliation_2026-09-12.md` |
| How a number was computed | `scripts_dinamr/` — the summary's own chunks are authoritative over any re-implementation |
| Cost and wall provenance | `scripts_dinamr/logs/`, `projectC.R`, `walls.R`, `wallsGC.R` |
| Part B: how `sg_focus` resolves per engine, MR-on cost bounds, host factor, Monte Carlo resolution | `REPORT_partB_measurement_2026-09-12.md`, `scripts_dinamr/partB_stage0_readout.R` |
| Part B: the `FS_S7_MR` change, Gate T3, the OC table, criterion agreement, the 288-cell-run projection | `REPORT_partB_enabling_2026-09-12.md`, `scripts_dinamr/partBoc_table.R`, `partBoc_checks.R` |
| Part B sweep: detection or selection, subgroup size, classification and criterion agreement for three engines × six criteria × 18 cells (MR off) | `summary_idsweep.html`, `REPORT_idsweep_2026-09-12.md`, `scripts_dinamr/logs/idsweep_findings.txt` |
| Part A: FS at `effMaxSG` ε 0.20 on the nine 12.4% cells — per-cell gate record, detection, classification, interval invariants | `p12x20_2026-09-12/REPORT_p12x20_A*.md` and `GATE2_p12x20_A*.txt`; campaign record `STATUS_p12x20.md` |
| The strict null: false-declaration rates, size, specificity both ways, `max_g T_g`, bound location | `REPORT_null_gbsg_identification_2026-09-21.md`; design point `scripts_dinamr/logs/nullid_designpoint.txt` |
| The strict null at the stricter screen c1 1.25 / c2 1.00, side by side with 0.90 / 0.80 | `REPORT_null_gbsg_thresholds_2026-09-21.md`; tables `scripts_dinamr/logs/nullc125_findings.md`; inertness `scripts_dinamr/logs/nullc125_inertness.txt` |
| The strict null with MR on: coverage of β(Ĥ) / β(Ĥᶜ) and where the adjusted lower bounds sit | `REPORT_null_gbsg_mr_2026-09-21.md`; tables `scripts_dinamr/logs/nullmr_findings.md`; identity gate `scripts_dinamr/logs/nullmr_identity.txt` |
| The calibrated declaration screen: family-wise declaration rates (boundary null, interior null, planted-harm power), `kappa_hat`, Eq. 8, the rounding band | `dev/reports/REPORT_declaration_calibration_evaluation_2026-09-22.md`; tables `scripts_dinamr/logs/declcal_findings.txt`; pilot `scripts_dinamr/logs/declcal_pilot_numbers.txt` |
| The calibrated screen at a clinically specified null level c0 (0.70–0.85): declaration rates, power, `kappa_hat(c0)` with implied p\*, `n_admitted`, fw_c0 | `dev/reports/REPORT_declcal_c0_campaign_2026-09-22.md`; tables `scripts_dinamr/logs/declcalc0_findings.txt`; approximate table `dev/reports/REPORT_declcal_c0_approx_2026-09-22.md` |
| The MR admission alignment's effect on the 18 Section 5 cells: per-replicate shift distributions, declaration identity, threshold crossings | `dev/reports/REPORT_mr_alignment_section5_sweep_2026-09-23.md`; table `mrs5sweep/readout.md` |
| The Section 5 FS cells re-run in full under the aligned package: per-cell shifts against the published bundles, and which quoted ranges move | `dev/reports/REPORT_section5_full_rerun_2026-09-24.md`; tables `s5rerun/readout.md`, `s5rerun/ranges.md` |
| Raw per-replicate rows | `results/*<campaign>*.rds`; `p12x20` in `p12x20_2026-09-12/` |

## 4. Reading conventions that must travel with these numbers

- Read every bound **by its location** against clinically meaningful effect sizes. Never frame a result as significance at HR = 1.00.
- **Selection rate is not an error rate.** At the differentially-null cells FS, DINA and GRF all select frequently and admissibly; GRF at 31% selects at 1 within its interval. What speaks to an unsupported claim is the share of lower bounds reaching HR 1.00 and 1.25.
  - **`nullid` (§2.8) settles what that rate is when there is genuinely nothing to find**: 0.1390-0.9845 against a structural null. A declaration rate near 1 is therefore compatible with no subgroup existing, and cannot on its own distinguish the two.
- **Under a structural null, conditional specificity is 1 - |Hhat|/n exactly** and carries no information beyond region size; quote the unconditional convention, or quote |Hhat|/n directly. Sensitivity and PPV are undefined there, and NPV is 1 by construction.
- Coverage and bias as one comparative table (cells × estimators), then a short plain-language reading, not narrative prose.
- Marginal SD and error SD side by side. A Gaussian reference on the marginal SD understates the prediction by up to 7.5 points where the target moves with the estimate; both forms are in the summaries with their formulas stated.
- Wilson intervals on every rate. A Wilson interval belongs on pooled subject-level counts or on a rate over replicates; a replicate-mean rate goes beside it without one.
- Cross-identifier comparisons are descriptive, never a ranking, and carry the confound: identifier, family construction, detection set, and at 12.4% the selection criterion.
- Evaluated estimator set: naive, oracle, IJ two-term, field, and Bonferroni for two-subgroup claims. Winner-only and winner-floor IJ variants are closed.
- `n_cons_qual`, `band_n` and `p_star` are structurally NA on DINA and GRF, not failures, and not on account of HR 1.00.
- On DINA and GRF, `eff` stands for `eff` = `maxeff` = `maxeffCons`: all three resolve to the plain effect argmax there, and the stem tags `eff`. Say so in every table.
- **A classification rate can be undefined.** NPV is NA when the selection is the whole trial, and PPV, sensitivity and specificity likewise when their denominator is zero. In `idsweep` this happens on DINA `maxSG` only. Report the count beside the mean; never read it as a recording failure.

## 5. Superseded or known-wrong — do not quote

The first three entries name files that live **outside this repository** (the `fs_glms_interpretable` workstream and the manuscript build). They are listed because their numbers circulate alongside this directory's, not because they are here. Only the entries after them are about files in `gbsg_020`.

- `claude/forestsearch_audit_spec.md` conditional-coverage figures: built from an earlier submission (different title, 35 + 85 pp.). The current build is 30 + 75 pp., dated 2026-08-20.
- Supplement §8.3 prose describing DINA/GRF conditional coverage as lower than FS's or recovering with n: does not agree with the adjacent tables and Figures S5/S7. Quote the tables and figures, not the prose.
- `BRIEF_dinamr_for_fs_glms_interpretable_2026-09-11.md` (v1): §8 listed FS classification metrics and bound-location shares as unavailable; both exist. Superseded by `BRIEF_fs_identifier_for_fs_glms_interpretable_2026-09-12.md`.
- `REVIEW_grfmr_2026-09-12.md` v1 framed its §2 as a blocking decision; withdrawn in the committed version.
- Earlier versions of this file: "`admitted_n` never 0 across 20,000 campaign replicates" is true of the harm cells only (see §2.4); "ρ(`admitted_n`, `n_family`) ≤ +0.042" was the ten-cell bound (now +0.054 over 18); "`grfmr` partial, 10 of 12, six null cells never run" is superseded by §2.3.
- **A reconciliation of the FS one-sided product ranges (2026-09-12; per-cell values in `REPORT_fs_products_reconciliation_2026-09-12.md`).** An earlier pass of this file "corrected" the certification figures; **two of those corrections were wrong and are withdrawn**. The certification records are correct as written and were not edited. What actually differs:
  - **field lower on β(Ĥ)** — a genuine **cell-set** difference. `NOTE_survival_products_2026-09-09.md` reports 0.944–0.974 over its harm cells. Its evidence list is `cert20` / `tier2` / `fixedphat_ij2s` / `field_studentize_e1` / `cimethod_flip` and does **not** include `REPORT_p12ext_2026-09-09`, the campaign that supplies the three 12.4% HR 1.50 cells. Excluding those, the committed bundles give exactly 0.944–0.974; including them gives 0.941–0.975, the 0.9410 coming from 12.4% HR 1.50 n 1000. *(The note says "ten harm cells"; nine is what reproduces the range, and no tenth bundle on disk carries field columns. Unreconciled, and it does not move the range.)*
  - **field-s upper on β(Ĥᶜ)** — **no difference at all.** The value is 0.9125–0.9605; "0.912–0.960" and "0.913–0.961" are the same endpoints rounded differently. The note's per-cell quotes reproduce exactly: 0.912 / 0.942 / 0.947 at 31% HR 1.50, 0.919 / 0.942 / 0.946 at HR 1.75, 0.941 / 0.956 / 0.961 at 12.4% HR 1.75.
  - **Bonferroni joint** — **different construction, not a different number.** The record's 0.939–0.963 is the **studentized** pair `fld_joint_s_bonf_*` (9-cell range 0.9395–0.9640). The 0.932–0.964 quoted against it was the **unscaled** pair `fld_joint_bonf_*`. Always name which.
  - Neither `SUMMARY_survival_properties_2026-09-10.md` nor `REVIEW_certification_2026-09-09.md` is in this repository, so the "0.941–0.980" attributed to them could not be checked. **0.980 does not reproduce from any field-lower computation on the committed bundles** (the nearest 0.98 in the record is the IJ two-sided at 31%, 0.971–0.981).
- **ε 0.10 as part of the 12.4% FS criterion (2026-09-12; `REPORT_partB_measurement_2026-09-12.md`, Stage 0b).** Reported; the records are not edited.
  - **What is wrong.** Several records treat ε 0.10 as operative on the `tier2` / `p12ext` cells:
    - `REPORT_dinamr_blockC_2026-09-11.md:596`: "at half the band width".
    - `summary_grfmr.qmd` captions: `fs_matched` / `criterion_matched` gated on "sg_focus and eps".
    - `REPORT_grfmr_completion_2026-09-12.md:257` and `REPORT_grfmr_2026-09-11.md:418`: "`maxeffCons` ε 0.10 against `effMaxSG` ε 0.20".
    - `fs_extraction.R`'s eps column.
  - **Why.** ε is inert under `maxeffCons`.
  - **Quote it as:** the 12.4% FS comparator differs from DINA and GRF in the **rule** (`maxeffCons`, no band).
- The `cert20` Stage 1 report's per-cell timing sums field-block seconds into `fit_mr_secs`, which already contains them. Those totals are double-counted. The `p12x20` Gate 1 report uses `fit_mr_secs` alone.
- **`REPORT_partB_enabling_2026-09-12.md`'s 500-replicate projection** ("11.1 h adjusted", quoted in §2.5) is the right arithmetic for its own method, but it is not an `idsweep` projection.
  - It counts a combine render per cell-run, which `idsweep` does not have.
  - It divides a host-mixed consistency profile by a pop-os value.
  - `REPORT_idsweep_2026-09-12.md` §2 gives the corrected basis (10.21 h) and the realized wall (12.01 h).
  - A "~13.6 h" figure, which multiplies render overhead by the cost ratio, is wrong.

## 6. Not derivable from the committed columns

- **DINA non-detection causes.** The recorder returns before `n_family` is written, so an empty proposal and a proposal with nothing admitted are indistinguishable. (On GRF they are separable through `admitted_n`: 0 versus NA.)
- **Per-subject membership**, so no classification metric finer than the four rates, and no agreement between two identifiers' Ĥ on the same draw.
- **2×2 counts** are not stored, but are exactly recoverable from the recorded rates with `n_sel` and `n_true` (checked to 5.68e-14).
- **`dinamr` render logs** were written to a session scratchpad that no longer exists. The compute wall is rebuildable from bundle timing columns (`walls.R`); the per-render overhead for that campaign is not.

## 7. Open work in this directory

- **`declcal` (§2.11), for review:** the task's §0 install assertion failed on a stale build and was cured by `devtools::install()` from HEAD rather than stopped on; the complete null uses a campaign-level `k_treat = 1e-10`; the `Z` capture relies on `trace()` (the fit returns neither `Z` nor `df.fs`); `B_cal = 500` sat exactly on the pilot rule's 0.005 boundary. Whether the calibrated screen becomes an operating rule is Larry's decision; the report records rates only.
- **GRF factor-membership exposure (`REPORT_grf_factor_exposure_2026-09-16.md`):** the `grfmr` survival results are not exposed to the `.grf_evaluate_subgroup()` factor defect found on the MD design — the simulated covariates are integer columns, sim_id 1 of A124_h150_n500 reproduces the committed selection with 0 NA memberships of 779 candidates, no applied document runs the GRF frontier on factor covariates, and DINA coerces or rejects factors before evaluation; the evaluator fix is Larry's decision.
- **Part B sweep `idsweep`: complete (§2.6). Two items for review:**
  - **Gate I Amendment 1**, applied unattended after the first Gate I stop. It allows a classification rate to be NA only where its denominator is zero, and counts each case. It needs Larry's acceptance or reversal; the rationale and the negative test are in `REPORT_idsweep_2026-09-12.md`.
  - **Push size.** The 288 `idsweep` renders total 1.09 GB (largest 3.81 MB; nothing over 50 MB).
  - Still not done: identification with MR on across the six criteria, and any criterion choice. The sweep carries no acceptance criterion and no recommendation.
- **A criterion-matched 12.4% FS comparator is now committed but not wired in.**
  - `p12x20` (§2.7) supplies FS at `effMaxSG` ε 0.20 with MR on at all nine 12.4% cells.
  - `idsweep` supplies FS identification and classification at those cells under `effMaxSG` ε 0.20 and `maxeffCons`, MR off.
  - `gate2G.R`, `fs_extraction.R` and the `dinamr` / `grfmr` summaries still designate `p12ext` / `tier2` at 12.4% (§2.1). Whether and how to repoint them is open.
- **`nullid` (§2.8): complete. Three items for review.**
  - **The design-point gate amendment**, applied unattended. The task fixed 1e-8 on check (3), the marginal-HR check; `dgm$hr_causal` is a `coxph` MLE on a 200,000-row stacked frame whose solver noise is ~8e-8 in absolute HR, so 1e-8 is below the numerical resolution of the quantity at the 0.657 design point (best attainable 1.155e-08; 0.721 reaches 2.722e-11). Check (3) asserts 1e-8, prints the outcome either way, and falls back to 1e-6 absolute on a miss. Checks (1) and (2) keep 1e-8 and pass at 1e-16 or exactly zero. Needs Larry's acceptance or reversal. Precedent: `idsweep` Gate I Amendment 1.
  - **`nv_H_*` / `nv_Hc_*` now populate with MR off.** This is what makes the unadjusted within-region estimate available without MR, but it changes what an MR-off render records: a future re-render of an `idsweep` cell would fill eight columns that are NA in the committed bundles. No existing value changes.
  - **Not done, deliberately:** the evaluation of Section 4's calibrated cutoff (the recorded `max_g T_g` makes it possible without a re-run), and a boundary null at uniform HR 1.00 — three more cells on this machinery, Larry's call.
- **`s5rerun` (§2.14):** whether the manuscript's Section 5 figures are regenerated from `s5rerun` (a tag change) — three range endpoints and several per-cell four-decimal values differ from the published bundles by one or two replicates; that regeneration belongs to the fs-glms-interpretable chats.
- Whether DINA and GRF should default to the field constructions, now informed by two complete 18-cell grids.
- Whether to pin a commit in `forestsearch_version`.
- The frontier-filter asymmetry decision (GRF's band as a filter with no empty-band fallback, where DINA uses a sort key and MR's `.inband()` has a "never empty" fallback) remains open; §2.4 states what can and cannot empty.
