data ___030_ds; set lptss.ds;
where dsgrpid IN ('DS01', 'PMS1');
RUN;

DATA ___030_SUPPDS; SET LPTSS.SUPPDS;
WHERE QNAM IN ('DSEPRELN' 'ADDDSDTL');
DSSEQ_ = INPUT(IDVARVAL, BEST.);
RUN;
PROC SORT;BY USUBJID DSSEQ_ QNAM;RUN;
PROC TRANSPOSE DATA=___030_SUPPDS OUT=___030_SUPPDS1;
BY USUBJID DSSEQ_;
ID QNAM;
VAR QVAL;
RUN;

PROC SQL;
CREATE TABLE ___030_DSPLUS AS SELECT A.*, B.DSEPRELN, B.ADDDSDTL
	FROM ___030_DS AS A LEFT JOIN ___030_SUPPDS1 AS B
		ON A.USUBJID = B.USUBJID AND A.DSSEQ = B.DSSEQ_;
QUIT;
