\Sexpr{set_parent("../../paper/Biostatistics_draft/forest_search_bio_v0.Rnw")}


<<echo=FALSE>>=
opts_chunk$set (warning = FALSE, message = FALSE, tidy=TRUE, echo=FALSE, dev = 'pdf')
options(warn=-1)
@

<<echo=FALSE>>=
rm(list=ls())

# Use common code source
codepath<-c("/media/larryleon/My Projects/GitHub/Forest-Search/R/")
source(paste0(codepath,"source_forestsearch_v0.R"))
source_fs_functions(file_loc=codepath)

# Data example output path
outpath<-c("/media/larryleon/My Projects/Current Projects/subgroup identification and analysis/applications/simulated_ex1/output/")

#library(formatR)
library(kableExtra)
library(knitr)
library(ggplot2)
library(gridExtra)
#library(covRobust)
# Following loaded in "forest_search_v0.R"
library(cubature)
library(aVirtualTwins)
library(randomForest)
library(survival)
library(survminer)
library(grf)
library(policytree)
library(data.table)
library(plyr)
library(dplyr)
library(glmnet)

#library(doRNG)
#library(doFuture)
@




<<r simsetup, echo=FALSE,eval=FALSE>>=
maxFollow<-84
cens.type<-"weibull"

# m1 -censoring adjustment
muC.adj<-log(1.5)
k.z3<-1.0
k.treat<-0.9

z1_frac<-0.25 # Default model index 'm1' (The 1st quartile of z1=er)
pH_super<-0.125 # non-NULL re-defines z1_frac

if(is.null(pH_super)){
#pH_check<-with(gbsg,mean(pgr<=quantile(pgr,c(z3_frac),1,0) & er<=quantile(er,z1_frac)))
pH_check<-with(gbsg,mean(meno==0 & er<=quantile(er,z1_frac)))
cat("Underlying pH_super",c(pH_check),"\n")
}
# pH_super specified
# If pH_super then override  z1_frac and find z1_frac to yield pH_super

if(!is.null(pH_super)){
  # Approximate Z1 quantile to yield pH proportion  
  z1_q<-uniroot(propH.obj4,c(0,1),tol=0.0001,pH.target=pH_super)$root
  #pH_check<-with(gbsg,mean(pgr<=quantile(pgr,c(z3_frac),1,0) & er<=quantile(er,z1_q)))
  pH_check<-with(gbsg,mean(meno==0 & er<=quantile(er,z1_q)))
  cat("pH",c(pH_check),"\n")
  rel_error<-(pH_super-pH_check)/pH_super
  if(abs(rel_error)>=0.1) stop("pH_super approximation relative error exceeds 10%")
  z1_frac<-z1_q
  cat("Underlying pH_super",c(pH_check),"\n")
  }

# Bootstrap on log(hr) scale converted to HR (est.loghr=TRUE & est.scale="hr")
est.loghr<-TRUE
est.scale<-"hr"
t.start.all<-proc.time()[3]

@


<<r AnalysisSetup, echo=FALSE,eval=FALSE>>=
#########################
# Forest search criteria
#########################
hr.threshold<-1.25   # Initital candidates 
hr.consistency<-1.0  # Candidates for many splits
pconsistency.threshold <- 0.9
stop.threshold <- 0.95
maxk<-2
nmin.fs<-60
pstop_futile<-0.5
# Limit timing for forestsearch
max.minutes<-3.0
m1.threshold<-Inf # Turning this off (Default)
#pconsistency.threshold<-0.70 # Minimum threshold (will choose max among subgroups satisfying)
fs.splits<-400 # How many times to split for consistency
# vi is % factor is selected in cross-validation --> higher more important
vi.grf.min<-0.2
# Null, turns off grf screening
d.min<-10 # Min number of events for both arms (d0.min=d1.min=d.min)
# default=5
##########################
# Virtual twins analysis
##########################
# Counter-factual difference (C-E) >= vt.threshold
# Large values in favor of C (control)
vt.threshold<-0.225  # For VT delta
treat.threshold<-0.0

maxdepth<-2
n.min<-60
ntree<-1000
# GRF criteria
dmin.grf<-12.0 # For GRF delta
# Note: For CRT this represents dmin.grf/2 RMS for control (-dmin.grf/2 for treatment)
frac.tau<-0.60

outcome.name<-c("y.sim")
event.name<-c("event.sim")
id.name<-c("id")
treat.name<-c("treat")

cox.formula.sim<-as.formula(paste("Surv(y.sim,event.sim)~treat"))
cox.formula.adj.sim<-as.formula(paste("Surv(y.sim,event.sim)~treat+v1+v2+v3+v4+v5"))
@



<<echo=FALSE,eval=FALSE>>=
# Bootstrap on log(hr) scale converted to HR (est.loghr=TRUE & est.scale="hr")
est.loghr<-TRUE
est.scale<-"hr"

out.loc<-NULL
model.index<-"m4a"
file.index<-"v0"


mod.harm<-"alt"
hrH.target <- 2.0

N <- 700
this.dgm<-get.dgm4(mod.harm=mod.harm,N=N,k.treat=k.treat,model.index="v0",
hrH.target=hrH.target,cens.type=cens.type,out.loc=out.loc,file.index=file.index,details=TRUE,parms_torand=FALSE)

@

<<echo=FALSE,eval=FALSE>>=

n_add_noise <- 3
sim <- 1 

dgm<-this.dgm$dgm

x<-sim_aftm4_gbsg(dgm=dgm,n=N,maxFollow=maxFollow,muC.adj=muC.adj,simid=sim)

  if(n_add_noise==0){
  confounders.name <- c("z1","z2","z3","z4","z5","size","grade")
  }
    
  if(n_add_noise==5){
  set.seed(8316951+1000*sim)
  # Add 5 noise 
  x$noise1 <- rnorm(N)
  x$noise2 <- rnorm(N)
  x$noise3 <- rnorm(N)
  x$noise4 <- rnorm(N)
  x$noise5 <- rnorm(N)
  confounders.name <- c("z1","z2","z3","z4","z5","size","grade","noise1","noise2","noise3","noise4","noise5")
  }
  
  if(n_add_noise==3){
    set.seed(8316951+1000*sim)
    # Add 3 noise 
    x$noise1 <- rnorm(N)
    x$noise2 <- rnorm(N)
    x$noise3 <- rnorm(N)
    confounders.name <- c("z1","z2","z3","z4","z5","size","grade","noise1","noise2","noise3")
  }


#cox.formula.check<-as.formula(paste("Surv(y.sim,event.sim)~treat+v1+v2+v3+v4+v5+noise1+noise2+noise3"))
#coxph(cox.formula.check,data=x)

# library(corrplot)
#Zm <- cor(x[,c(confounders.name)])
#corrplot(Zm)

use_lasso <- TRUE
use_grf <- TRUE

conf_force <- NULL
grf_depth <- 2

fs.est <- forestsearch(df.analysis=x, Allconfounders.name=confounders.name,
details=TRUE,use_lasso=use_lasso, use_grf=use_grf,
conf_force=conf_force, grf_depth=grf_depth,
outcome.name=outcome.name,treat.name=treat.name,event.name=event.name,id.name=id.name,
n.min=nmin.fs,hr.threshold=hr.threshold,hr.consistency=hr.consistency,fs.splits=fs.splits,
d0.min=d.min,d1.min=d.min,pstop_futile=pstop_futile,
pconsistency.threshold=pconsistency.threshold, stop.threshold=stop.threshold,
max.minutes=max.minutes,maxk=maxk,by.risk=12,
plot.sg=TRUE,vi.grf.min=vi.grf.min)

grf.est <- grf.subg.harm.survival(data=x,confounders.name=confounders.name,outcome.name=outcome.name,
event.name=event.name,id.name=id.name,treat.name=treat.name,n.min=n.min,
dmin.grf=dmin.grf,frac.tau=0.6, maxdepth=grf_depth, details=TRUE)

library(doParallel)
registerDoParallel(parallel::detectCores(logical = FALSE))

cox.formula.boot<-cox.formula.sim
est.loghr<-TRUE
max.minutes<-7.0
# Suggest running 50, first ... to get timing estimate

NB<-100
df_boot_analysis <- fs.est$df.est
#################################
# est.loghr=T --> log(HR) scale
#################################
fitH<-get_Cox_sg(df_sg=subset(df_boot_analysis,treat.recommend==0),cox.formula=cox.formula.boot,est.loghr=est.loghr)
H_obs<-fitH$est_obs # log(hr) scale
seH_obs<-fitH$se_obs
# Hc observed estimates
fitHc<-get_Cox_sg(df_sg=subset(df_boot_analysis,treat.recommend==1),cox.formula=cox.formula.boot,est.loghr=est.loghr)
Hc_obs<-fitHc$est_obs
seHc_obs<-fitHc$se_obs
rm("fitH","fitHc")

Ystar_mat<-bootYstar(
{  
ystar<-get_Ystar(boot)
},
boots=NB,
seed=8316951,
counter="boot",
export=fun_arg_list_boot
)
# Check dimension
if(dim(Ystar_mat)[1]!=NB | dim(Ystar_mat)[2]!=nrow(df_boot_analysis)) stop("Dimension of Ystar_mat does not match")

tB.start<-proc.time()[3]
# Bootstraps
resB<-bootPar(
{  
ans<-fsboot_forparallel(boot)
},
boots=NB,
seed=8316951,
counter="boot",
export=fun_arg_list_boot
)
tB.now<-proc.time()[3]
tB.min<-(tB.now-tB.start)/60

doParallel::stopImplicitCluster()

cat("Minutes for Boots",c(NB,tB.min),"\n")
cat("Projection per 100",c(tB.min*(100/NB)),"\n")
cat("Propn bootstrap subgroups found =",c(sum(!is.na(resB$H_biasadj_1))/NB),"\n")
# How many timmed out 
cat("Number timmed out=",c(sum(is.na(resB$H_biasadj_1) & resB$tmins_search>max.minutes)),"\n")

H_estimates<-get_dfRes(Hobs=H_obs,seHobs=seH_obs,H1_adj=resB$H_biasadj_1,ystar=Ystar_mat,cov_method="standard",cov_trim=0.05)

Hc_estimates<-get_dfRes(Hobs=Hc_obs,seHobs=seHc_obs,H1_adj=resB$Hc_biasadj_1,ystar=Ystar_mat,cov_method="standard",cov_trim=0.05)

print(H_estimates)
print(Hc_estimates)

bootit<-list(H_estimates=H_estimates,Hc_estimates=Hc_estimates)
ans3<-fsBoot.parallel.out(df=df_boot_analysis,FSboots=bootit,cox.formula.boot=cox.formula.boot,est.loghr=est.loghr,sim_number=sim)

# Revise path accordingly
#save(dgm,x,y,H_estimates,Hc_estimates,ans3,file="output/sim_ex1.Rdata")
@

<<echo=FALSE,eval=TRUE>>=
load(paste0(outpath,"sim_ex1.Rdata"))
@




<<echo=FALSE,eval=TRUE>>=
df_pred<-fs.est$df.predict
df<-df_pred
tte.name<-"y.sim"
event.name<-"event.sim"
treat.name<-"treat"
byrisk<-9
risk.cex<-0.6
legend.cex<-0.75
details<-TRUE
ylab<-"Survival"
# Add all events
evs<-sort(unique(df$y.sim[which(df$event.sim==1)]))
tpoints.add<-c(-1,evs,max(df$y.sim))
pcens<-100*round(mean(1-df$event.sim),2)
nn<-length(df$y.sim)
nH_true<-sum(x$flag.harm)
nHc_true<-sum(1-x$flag.harm)
nH_est<-sum(1-df$treat.recommend)
kH<-with(df,sum(treat.recommend==0 & flag.harm==1))
sens_H<-kH/nH_true
spec_H<-kH/nH_est

nHc_est<-sum(df$treat.recommend)
kHc<-with(df,sum(treat.recommend==1 & flag.harm==0))

pH_super<-100*round(mean(dgm$df.super_rand$flag.harm),2)

#ans3b<-format(ans3,digits=4,drop0trailing=TRUE)
#ans3<-as.data.frame(ans3b)

ans3<-round(ans3,3)

# ITT estimates
resITT<-c(ans3[,c("H_itt","H_itt_lower","H_itt_upper")],NA,NA)

# Knowing subgroup a-priori
# Returns coverage status for hr.H.true
# coverage for a-prior is NA
temp<-getci_Cox(df=as.data.frame(ans3),est="H_true",se="seH_true",target=unlist(dgm["hr.H.true"]))
resH_apriori<-c(ans3[,c("H_true")],temp$lb,temp$ub,NA,temp$cover)
###########
# Observed
###########
temp<-getci_Cox(df=as.data.frame(ans3),est="H_obs",se="seH_obs",target=unlist(dgm["hr.H.true"]))
# Cover a-priori ?
estH_apriori<-ans3[,c("H_true")]
cover2<-ifelse(estH_apriori >= c(temp$lb) & estH_apriori <= c(temp$ub),1,0)
resH_obs<-c(ans3[,c("H_obs")],temp$lb,temp$ub,cover2,temp$cover)
# Bias-corrected
temp<-getci_Cox(df=as.data.frame(ans3),est="H1.bc",se="seH1.bc",target=unlist(dgm["hr.H.true"]))
# Cover a-priori ?
cover2<-ifelse(estH_apriori >= c(temp$lb) & estH_apriori <= c(temp$ub),1,0)
resH_bc<-c(ans3[,c("H1.bc")],temp$lb,temp$ub,cover2,temp$cover)
###########################################
resH<-rbind(resH_apriori,resH_obs,resH_bc)
###########################################
# Repeat above for Hc
temp<-getci_Cox(df=as.data.frame(ans3),est="Hc_true",se="seHc_true",target=unlist(dgm["hr.Hc.true"]))
resH_apriori<-c(ans3[,c("Hc_true")],temp$lb,temp$ub,NA,temp$cover)
temp<-getci_Cox(df=as.data.frame(ans3),est="Hc_obs",se="seHc_obs",target=unlist(dgm["hr.Hc.true"]))
estH_apriori<-ans3[,c("Hc_true")]
cover2<-ifelse(estH_apriori >= c(temp$lb) & estH_apriori <= c(temp$ub),1,0)
resH_obs<-c(ans3[,c("Hc_obs")],temp$lb,temp$ub,cover2,temp$cover)
temp<-getci_Cox(df=as.data.frame(ans3),est="Hc1.bc",se="seHc1.bc",target=unlist(dgm["hr.Hc.true"]))
cover2<-ifelse(estH_apriori >= c(temp$lb) & estH_apriori <= c(temp$ub),1,0)
resH_bc<-c(ans3[,c("Hc1.bc")],temp$lb,temp$ub,cover2,temp$cover)
###########################################
resHc<-rbind(resH_apriori,resH_obs,resH_bc)
###########################################

res<-rbind(resITT,resH,resHc)
resf<-as.data.frame(res)
colnames(resf)<-c("HR Estimate","Lower","Upper","C(true)","C(fixed)")

# Per Keaven's suggestion, remove C(.) and include # of subjects

resf_new<-resf[,-c(4,5)]
# Add sample size columns
na<-c(nn,nH_true,nH_est,nH_est,nHc_true,nHc_est,nHc_est)
ncorrect<-c(NA,NA,kH,kH,NA,kHc,kHc)
nnew<-cbind(na,ncorrect)
resf_new<-cbind(resf_new,nnew)

rm("resf")

colnames(resf_new)<-c("HR Estimate","Lower","Upper","$\\#$ Subjects","$\\#$ Correct")
resf<-resf_new

#rnH<-c("$\\hat\\theta(H)$","$\\hat\\theta(\\hat{H})$","$\\hat\\theta^{*}(\\hat{H})$")
#rnHc<-c("$\\hat\\theta(H^{c})$","$\\hat\\theta(\\hat{H}^{c})$","$\\hat\\theta^{*}(\\hat{H}^{c})$")
#rnItt<-c("$\\hat\\theta(ITT)$")

rnH<-c("H true","$\\hat{H}$","$\\hat{H}_{bc}$")
rnHc<-c("$H^{c}$ true","$\\hat{H}^{c}$","$\\hat{H}^{c}_{bc}$")
rnItt<-c("ITT")

rownames(resf)<-c(rnItt,rnH,rnHc)

# Describing CIs
Hstat<-c(unlist(resH[1,]))[c(1,2,3)]
Hstat<-round(Hstat,2)
a<-paste0(Hstat[1]," (95% CI=")
a<-paste0(a,Hstat[2])
a<-paste0(a,",")
a<-paste0(a,Hstat[3])
a<-paste0(a,")")
Hstat_true<-c(a)

Hstat<-c(unlist(resH[2,]))[c(1,2,3)]
Hstat<-round(Hstat,2)
a<-paste0(Hstat[1]," (95% CI=")
a<-paste0(a,Hstat[2])
a<-paste0(a,",")
a<-paste0(a,Hstat[3])
a<-paste0(a,")")
Hstat_est<-c(a)

Hstat<-c(unlist(resH[3,]))[c(1,2,3)]
Hstat<-round(Hstat,2)
a<-paste0(Hstat[1]," (95% CI=")
a<-paste0(a,Hstat[2])
a<-paste0(a,",")
a<-paste0(a,Hstat[3])
a<-paste0(a,")")
Hstat_bc<-c(a)

@

<<simex1_tab,echo=FALSE,eval=FALSE>>=
options(knitr.kable.NA = '.',format="latex")
tab_ex1<-kbl(resf,longtable=FALSE,align='c',format="latex",booktabs=TRUE,escape=F,digits=3,
caption="\\label{tab:simex1} Simulated data example: Cox hazard ratio (hr) estimates for the ITT population and subgroups $H$ and $H^{c}$.
Cox model estimates are based on subgroups: H true (knowing the actual subgroup, a-priori); the estimated subgroup $\\hat{H}$; and 
the boostrap ($500$ resamples) bias-correction to $\\hat{H}$ estimates, denoted $\\hat{H}_{bc}$.  Estimates for the complement $H^{c}$ are defined analogously.
The number of subjects in each population ($\\#$ Subjects) and the number of subjects correctly classified ($\\#$ Correct) in the true subgroups $H$ and $H^{c}$, respectively, are listed.") %>%
kable_styling(full_width = FALSE, font_size=9) %>%
group_rows("ITT", 1, 1) %>%
group_rows("H subgroup estimates", 2, 4) %>%
group_rows("H-complement subgroup estimates", 5, 7)
@



\begin{table}[p]
\caption{\label{tab:simex1} Simulated data example: Cox hazard ratio (hr) estimates for the ITT population and subgroups $H$ and $H^{c}$.
Cox model estimates are based on subgroups: H true (knowing the actual subgroup, a-priori); the estimated subgroup $\hat{H}$; and 
the boostrap ($500$ resamples) bias-correction to $\hat{H}$ estimates, denoted $\hat{H}_{bc}$.  Estimates for the complement $H^{c}$ are defined analogously.
The number of subjects in each population ($\#$ Subjects) and the number of subjects correctly classified ($\#$ Correct) in the true subgroups $H$ and $H^{c}$, respectively, are listed.}
\centering
\fontsize{9}{11}\selectfont
\begin{tabular}[t]{lccccc}
\toprule
  & HR Estimate & Lower & Upper & $\#$ Subjects & $\#$ Correct\\
\midrule
\addlinespace[0.3em]
\multicolumn{6}{l}{\textbf{ITT}}\\
\hspace{1em}ITT & 0.838 & 0.687 & 1.021 & 700 & .\\
\addlinespace[0.3em]
\multicolumn{6}{l}{\textbf{H subgroup estimates}}\\
\hspace{1em}H true & 2.358 & 1.471 & 3.781 & 101 & .\\
\hspace{1em}$\hat{H}$ & 3.077 & 1.604 & 5.904 & 64 & 52\\
\hspace{1em}$\hat{H}_{bc}$ & 2.248 & 1.436 & 3.519 & 64 & 52\\
\addlinespace[0.3em]
\multicolumn{6}{l}{\textbf{H-complement subgroup estimates}}\\
\hspace{1em}$H^{c}$ true & 0.672 & 0.537 & 0.841 & 599 & .\\
\hspace{1em}$\hat{H}^{c}$ & 0.733 & 0.592 & 0.908 & 636 & 587\\
\hspace{1em}$\hat{H}^{c}_{bc}$ & 0.743 & 0.592 & 0.932 & 636 & 587\\
\bottomrule
\end{tabular}
\end{table}

As a practical illustration we consider a simulated dataset generated as described in Section \ref{sec:sims}.   In this simulated example there are 
$N=\Sexpr{length(df$y.sim)}$ subjects, randomized 1:1, where the underlying (marginal) hazard ratio for the harm population $H$ is 
$\hplim =\Sexpr{round(dgm$hr.H.true,3)}$, and for the complement $H^{c}$, the (marginal) hazard ratio is $\hcplim =\Sexpr{round(dgm$hr.Hc.true,3)}$.  The overall (marginal) hazard ratio is $\Sexpr{round(dgm$hr.causal,2)}$.  
Subjects' outcomes are generated from a Weibull regression model with $5$ covariates, and analysis is based on those $5$ covariates in addition to $2$ ``noise'' covariates.
The underlying proportion of subjects in the harm population $H$ is $\approx \Sexpr{pH_super}\%$.  Here the actual number of subjects in the $H$ subgroup is $\Sexpr{sum(x$flag.harm)}$ and the number of subjects in the complement equals $\Sexpr{sum(1-x$flag.harm)}$.  



\begin{figure}[p]
\begin{center}
<<simex1_fig,echo=FALSE,out.height="250px",out.width="400px">>=
library(latex2exp)
#layout(matrix(c(1,2), 1, 2, byrow = TRUE),widths=c(1,1.25),heights=c(1,1))
#par(mfrow=c(1,2), mai = c(1,0.1,0.1,0.1)) 

# mar: bottom,left,top, right margins

par(mar=c(5, 0.5, 0.2, 0.2), mfrow=c(1,2),
     oma = c(4, 4, 0.2, 0.2))

# First, true H subgroup (flag.harm==1) and 
# estimates H subgroup (treat.recommend==0)
# Treat arms for H subgroup
dfp<-subset(df,flag.harm==1)

kmH.fit<-KM.plot.2sample.weighted(Y=dfp[,c(tte.name)],E=dfp[,c(event.name)],Treat=dfp[,c(treat.name)],
risk.set=FALSE,by.risk=byrisk,tpoints.add=tpoints.add,risk.cex=risk.cex,
stop.onerror=TRUE,Xlab="Months",Ylab="Survival",details=FALSE,
show.ticks=FALSE,
col.1="grey", col.2="grey",
ltys=c(1,2),lwds=c(3,3),
plotit=TRUE,
show.logrank=FALSE,show.med=FALSE,show.cox=FALSE)
title(sub="(a)")

# Risk set for true H
riskH<-kmH.fit$risk.1+kmH.fit$risk.2
riskH.points<-kmH.fit$risk.points
# put on top
y.riskH<-kmH.fit$y.risk2
text(c(riskH.points),c(y.riskH),c(riskH),col="grey",cex=risk.cex)

dfp<-subset(df,treat.recommend==0)
# Do not plot (plotit=FALSE)
kmHest.fit<-KM.plot.2sample.weighted(Y=dfp[,c(tte.name)],E=dfp[,c(event.name)],Treat=dfp[,c(treat.name)],
risk.set=FALSE,by.risk=byrisk,tpoints.add=tpoints.add,risk.cex=risk.cex,
stop.onerror=TRUE,Xlab="Months",Ylab=ylab,details=FALSE,
show.ticks=FALSE,
col.1="grey", col.2="grey",
ltys=c(1,2),lwds=c(3,3),
plotit=FALSE,
show.logrank=FALSE,show.med=FALSE,show.cox=FALSE)

lwdHe<-3

# Treatment arm, H estimated
lines(kmHest.fit$at.points1.plot,kmHest.fit$Y1.plot,lty=1,type="s",col="black",lwd=lwdHe)
# Control arm, H estimated
lines(kmHest.fit$at.points2.plot,kmHest.fit$Y2.plot,lty=2,type="s",col="black",lwd=lwdHe)

# Risk set for estimated H
riskHest<-kmHest.fit$risk.1+kmHest.fit$risk.2
riskHest.points<-kmHest.fit$risk.points
# put on top
y.riskHest<-kmHest.fit$y.risk1
text(c(riskHest.points),c(y.riskHest),c(riskHest),col="black",cex=risk.cex)

#legend("top",legend=c("H true, Treatment","est(H), Treatment","H true, Control","est(H), Control"),col=c("grey","black","grey","black"),lwd=c(3,lwdHe,3,lwdHe),lty=c(1,1,2,2),bty="n",cex=legend.cex)

#legend("top",
#legend=TeX(sprintf(r'($H, %s$)',c("Treatment","Treatment","Control","Control"))),
#col=c("grey","black","grey","black"),lwd=c(3,lwdHe,3,lwdHe),lty=c(1,1,2,2),bty="n",cex=legend.cex)

Hla<-sprintf(r'($H, %s$)',c("Treatment"))
Hlb<-sprintf(r'($\hat{H}, %s$)',c("Treatment"))
Hlc<-sprintf(r'($H, %s$)',c("Control"))
Hld<-sprintf(r'($\hat{H}, %s$)',c("Control"))
Hl<-c(Hla,Hlb,Hlc,Hld)

legend("top",
legend=TeX(Hl),col=c("grey","black","grey","black"),lwd=c(3,lwdHe,3,lwdHe),lty=c(1,1,2,2),bty="n",cex=legend.cex)


# Complement

# Keep same naming below (i.e., H is now H-complement)

# Treat arms for H subgroup
dfp<-subset(df,flag.harm==0)

kmH.fit<-KM.plot.2sample.weighted(Y=dfp[,c(tte.name)],E=dfp[,c(event.name)],Treat=dfp[,c(treat.name)],
risk.set=FALSE,by.risk=byrisk,tpoints.add=tpoints.add,risk.cex=risk.cex,
stop.onerror=TRUE,Xlab="Months",Ylab="Survival",details=FALSE,
show.ticks=FALSE,
col.1="grey", col.2="grey",
ltys=c(1,2),lwds=c(3,3),
plotit=TRUE,
show.Y.axis=FALSE,
show.logrank=FALSE,show.med=FALSE,show.cox=FALSE)

title(sub="(b)")

# Risk set for true H
riskH<-kmH.fit$risk.1+kmH.fit$risk.2
riskH.points<-kmH.fit$risk.points
# put on top
y.riskH<-kmH.fit$y.risk2
text(c(riskH.points),c(y.riskH),c(riskH),col="grey",cex=risk.cex)

dfp<-subset(df,treat.recommend==1)
# Do not plot (plotit=FALSE)
kmHest.fit<-KM.plot.2sample.weighted(Y=dfp[,c(tte.name)],E=dfp[,c(event.name)],Treat=dfp[,c(treat.name)],
risk.set=FALSE,by.risk=byrisk,tpoints.add=tpoints.add,risk.cex=risk.cex,
stop.onerror=TRUE,Xlab="Months",Ylab=ylab,details=FALSE,
show.ticks=FALSE,
col.1="grey", col.2="grey",
ltys=c(1,2),lwds=c(3,3),
plotit=FALSE,
show.logrank=FALSE,show.med=FALSE,show.cox=FALSE)

# Treatment arm, H estimated
lines(kmHest.fit$at.points1.plot,kmHest.fit$Y1.plot,lty=1,type="s",col="black",lwd=lwdHe)
# Control arm, H estimated
lines(kmHest.fit$at.points2.plot,kmHest.fit$Y2.plot,lty=2,type="s",col="black",lwd=lwdHe)

# Risk set for estimated H
riskHest<-kmHest.fit$risk.1+kmHest.fit$risk.2
riskHest.points<-kmHest.fit$risk.points
# put on top
y.riskHest<-kmHest.fit$y.risk1
text(c(riskHest.points),c(y.riskHest),c(riskHest),col="black",cex=risk.cex)

Hla<-sprintf(r'($H^{c}, %s$)',c("Treatment"))
Hlb<-sprintf(r'($\hat{H}^{c}, %s$)',c("Treatment"))
Hlc<-sprintf(r'($H^{c}, %s$)',c("Control"))
Hld<-sprintf(r'($\hat{H}^{c}, %s$)',c("Control"))
Hl<-c(Hla,Hlb,Hlc,Hld)

legend("top",
legend=TeX(Hl),col=c("grey","black","grey","black"),lwd=c(3,lwdHe,3,lwdHe),lty=c(1,1,2,2),bty="n",cex=legend.cex)
@
\end{center}
\caption{Simulated data example with $\approx \Sexpr{pcens}$\% censoring: (a) Kaplan-Meier (KM) curves for the true $H$ ($H$) subgroup for the treatment (solid grey) 
and control (dashed grey) arms, along with the KM curves for the estimated H ($\hat{H}$) subgroup treatment (solid black) and control (dashed black); 
(b) KM curves for the true complement $H^{c}$ ($H^{c}$) subgroup for the treatment (solid grey) 
and control (dashed grey) arms, along with the KM curves for the estimated $H^{c}$ ($\hat{H}^{c}$) subgroup treatment (solid black) and control (dashed black). The displayed risk sets 
correspond to the treatment and control arms combined for the true and estimated subgroups ($H$ and $\hat{H}$ in (a); $H^{c}$ and $\hat{H}^{c}$ in (b)).}\label{fig:simex1}
\end{figure}



Applying our novel procedure the estimated subgroup $\hat{H}$ consists of $\Sexpr{nH_est}$ subjects and thus 
$\Sexpr{nn-nH_est}$ in the estimated complement $\hat{H}^{c}$. The number of subjects in $H$ that are included in $\hat{H}$ is $\Sexpr{kH}$ (i.e., $|H \cap \hat{H}|=\Sexpr{kH}$): Of the $\Sexpr{nH_true}$ subjects in $H$, $\Sexpr{kH}/\Sexpr{nH_true}=\Sexpr{100*round(kH/nH_true,3)}\%$ are correctly classified and of the $\Sexpr{nH_est}$ subjects in $\hat{H}$, $\Sexpr{kH}/\Sexpr{nH_est}=\Sexpr{100*round(kH/nH_est,3)}\%$ are correctly classified.  For the complement, the number of subjects in $H^{c}$ that are included in $\hat{H}^{c}$ is $\Sexpr{kHc}$: Of the $\Sexpr{nHc_true}$ subjects in $H^{c}$, $\Sexpr{kHc}/\Sexpr{nHc_true}=\Sexpr{100*round(kHc/nHc_true,3)}\%$ are correctly classified and of the $\Sexpr{nHc_est}$ subjects in $\hat{H}^{c}$, $\Sexpr{kHc}/\Sexpr{nHc_est}=\Sexpr{100*round(kHc/nHc_est,3)}\%$ are correctly classified.  

In other words, $\hat{H}^{c}$ represents $\Sexpr{100*round(kHc/nHc_true,3)}\%$ of $H^{c}$, and for estimation (Cox and Kaplan-Meier)
based on $\hat{H}^{c}$: $\Sexpr{100*round(kHc/nHc_est,3)}\%$ are $H^{c}$ subjects with (marginal) hazard ratio $\hcplim=\Sexpr{round(dgm$hr.Hc.true,3)}$, and $\Sexpr{100*round(1-kHc/nHc_est,3)}\%$
are $H$ subjects with (marginal) hazard ratio $\hplim =\Sexpr{round(dgm$hr.H.true,3)}$.
%In the sequel we refer to these as specificity and sensitivity metrics for $\hat{H}$, and $\hat{H}^{c}$.

%\Sexpr{tab_ex1}


Figure \ref{fig:simex1} displays the Kaplan-Meier curves based on the true (known a-priori) subgroups and the estimated subgroups (Figures \ref{fig:simex1}(a) and \ref{fig:simex1}(b), for $H$ and $H^{c}$, respectively).  The Kaplan-Meier curves for the treatment and control arms for the actual subgroups ($H$, known a-prior) are generally well characterized by the estimated subgroups.  


Table \ref{tab:simex1} provides the Cox estimate for the overall population (ITT) as well as the estimates based on the true (known a-priori), and estimated subgroups, $\hat{H}$ and $\hat{H}^{c}$.  The ITT Cox estimate is $\Sexpr{round(as.numeric(resITT[1]),2)}$ (95\% CI=$\Sexpr{round(as.numeric(resITT[2]),2)}$, $\Sexpr{round(as.numeric(resITT[3]),2)}$), 
which is statistically insignificant and highlights the practical implications.  For characterizing $H$, recall that the underlying (marginal) hazard ratio is $\hplim =\Sexpr{round(dgm$hr.H.true,2)}$.  If the true H is known (a-priori), the Cox estimate is $\Sexpr{round(as.numeric(resH[1,1]),2)}$ (95\% CI=$\Sexpr{round(as.numeric(resH[1,2]),2)}$, $\Sexpr{round(as.numeric(resH[1,3]),2)}$), and for the estimated H, $\hat{H}$, the Cox estimate is $\Sexpr{round(as.numeric(resH[2,1]),2)}$ (95\% CI=$\Sexpr{round(as.numeric(resH[2,2]),2)}$, 
$\Sexpr{round(as.numeric(resH[2,3]),2)}$).  By the nature of the FS procedure we expect Cox model estimates based on an estimated subgroup to be upwardly biased for $H$.  We therefore describe a bootstrap bias-correction, which in this case, the bias-corrected Cox estimate denoted by $\hat{H}_{bc}$ is $\Sexpr{round(as.numeric(resH[3,1]),2)}$ (95\% CI=$\Sexpr{round(as.numeric(resH[3,2]),2)}$, $\Sexpr{round(as.numeric(resH[3,3]),2)}$) which we see provides a more ``tempered''estimate and is quite similar to the estimates based on the ideal true H in this simulated example.  
In addition, notice that the CIs for each estimate cover the underlying (marginal) respective hazard ratios 
$\hplim =\Sexpr{round(dgm$hr.H.true,2)}$ and $\hcplim =\Sexpr{round(dgm$hr.Hc.true,2)}$ for $H$ and $H^{c}$, respectively.  
The CIs for $\hat{H}$ and $\hat{H}_{bc}$ also cover the estimate based on $H$ true =  $\Sexpr{round(as.numeric(resH[1,1]),2)}$; and similarly for the complement where $H^{c}$ true =  $\Sexpr{round(as.numeric(resHc[1,1]),2)}$.  We remark that this simulated example is representative of the results observed in our simulation setting described in Section \ref{sec:sims}.




