\documentclass[9pt]{article}
\usepackage{amsmath}
\usepackage{graphicx}

\textheight=9.0in \textwidth=6.0in 
\topmargin=0in
\evensidemargin=0in \oddsidemargin=0in


\def\eqalign#1{\null\,\vcenter{\openup\jot
\ialign{\strut\hfil$\displaystyle{##}$&$ \displaystyle{{}##}$\hfil
\crcr#1\crcr}}\,}

\begin{document}

<<echo=FALSE>>=
#.libPaths("C:/Users/leolarr2/OneDrive - Merck Sharp & Dohme, Corp/documents/MyRlibrary")
#library(tinytex)
#library(knitr)

print(getwd())

@


<<echo=FALSE>>=

hist(rnorm(100))
@




\end{document}



